### ISSUE TITLE
404 Not Found: @vuepress/theme-vue

### ISSUE THREAD

**Issue by sharanraj124** [vuejs/vuepress#1003]
this is not issue.  I install the package this type error is shown and I not show side bar and nav links
```
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code E404
npm ERR! 404 Not Found: @vuepress/theme-vue@^1.0.0-alpha.20

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/appleapple/.npm/_logs/2018-11-14T13_03_21_071Z-debug.log
```

**Comment by sharanraj124** [comment]
I use custom theme, I get this type of error.

```
 WAIT  Extracting site metadata...
Error: [vuepress] Failed to load custom theme "@vuepress/theme-default". File vuepress-theme-@vuepress/theme-default/Layout.vue does not exist.
    at resolveOptions (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/lib/prepare/resolveOptions.js:69:15)
    at prepare (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/lib/prepare/index.js:11:25)
    at dev (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/lib/dev.js:23:25)
    at args (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/bin/vuepress.js:105:12)
    at Command.program.command.description.option.option.option.action (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/bin/vuepress.js:32:21)
    at Command.listener (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/node_modules/commander/index.js:654:12)
    at Command.parse (/Users/appleapple/.nvm/versions/node/v8.12.0/lib/node_modules/vuepress/node_modules/commander/index.js:474:21)
```

**Comment by ulivz** [comment]
@shaodahong Using custom theme? so why VuePress loaded `"@vuepress/theme-default`?

if `"@vuepress/theme-default"` cannot be loaded, using the latest version instead.

**Comment by sharanraj124** [comment]
ok, i have some doubts,
I use multiple sidebar but is it not linking one to another directory how to solve it
