### ISSUE TITLE
dependency library ajv has a broken change

### ISSUE THREAD

**Issue by dodocat** [vuejs/vuepress#1056]
when I run  `vuepress dev` got error:

```
 WAIT  Extracting site metadata...
Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/cindy/.config/yarn/global/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

check ajv repo, find out `equal.js` has been removed https://github.com/epoberezkin/ajv/commit/f9fcc504a4aaee3653af0f61c7681e2e80557f67

**Comment by ulivz** [comment]
This commit has been reverted and release at `6.6.1`.
