### ISSUE TITLE
Not work with symbolic file

### ISSUE THREAD

**Issue by kamontat** [vuejs/vuepress#1078]
- [X] I confirm that this is a issue rather than a question.

#### Version 

0.14.8

#### Steps to reproduce

Create symbolic README.md file

#### What is expected?

generate the content in files

#### What is actually happening?

Error: 

```
Error: ELOOP: too many symbolic links encountered, stat '/Users/kamontat/Desktop/Projects/Portfolio/gh-pages/CHANGELOG.md'
Emitted 'error' event at:
    at FSWatcher._handleError (/Users/kamontat/Desktop/Projects/Portfolio/node_modules/chokidar/index.js:260:10)
    at FSWatcher.<anonymous> (/Users/kamontat/Desktop/Projects/Portfolio/node_modules/chokidar/lib/fsevents-handler.js:280:14)
    at fs.js:1614:23
    at FSReqWrap.oncomplete (fs.js:154:21)
```

#### Other relevant information

- Your OS: macOS Mojave 10.14.1 18B75 x86_64
- Node.js version: v10.14.1
- Browser version: Chrome Version 71.0.3578.75 (Official Build) beta (64-bit)
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Ref: https://github.com/webpack/webpack/issues/1643
