### ISSUE TITLE
Google Analytics Plugin Build Error

### ISSUE THREAD

**Issue by limdongjin** [vuejs/vuepress#1126]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha.30

#### Steps to reproduce

package.json
```json
 {
   "dependencies": {
     "@vuepress/plugin-google-analytics": "^1.0.0-alpha.0"
   }
 }
```
.vuepress/config.js
```js
// .vuepress/config.js
module.exports = {
    title: "Google Analytics Build Error",
    description: "foo",
    plugins: [
       ['@vuepress/google-analytics',{
            ga: 'UA-xxxxxxx'
        }]
    ]
}
```
README.md
```md
---
home: true
---
# HOME READMD
```

Run `vuepress build`
```
Rendering page: /ReferenceError: window is not defined
    at inject (server-bundle.js:4080:8)
    at server-bundle.js:4556:9
    at Array.forEach (<anonymous>)
    at createApp (server-bundle.js:4554:19)
    at module.exports.__webpack_exports__.default (server-bundle.js:4594:22)
    at new Promise (<anonymous>)
    at module.exports.__webpack_exports__.default (server-bundle.js:4593:10)
    at /Users/imdongjin/.config/yarn/global/node_modules/vue-server-renderer/build.js:8456:15
    at new Promise (<anonymous>)
    at /Users/imdongjin/.config/yarn/global/node_modules/vue-server-renderer/build.js:8418:14
    at Object.renderToString (/Users/imdongjin/.config/yarn/global/node_modules/vue-server-renderer/build.js:8594:9)
    at renderPage (/Users/imdongjin/.config/yarn/global/node_modules/@vuepress/core/lib/build.js:151:29)
    at build (/Users/imdongjin/.config/yarn/global/node_modules/@vuepress/core/lib/build.js:76:26)
```
#### Other relevant information

- Your OS: Mac 10.14
- Node.js version: 10.6.0
- plugin-google-analytics: 1.0.0-alpha.0
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by mAKEkr** [comment]
this error has solved on latest plugin version. fix your `package.json` and you can try to build command in latest version of this plugin.

**Comment by ulivz** [comment]
As mentioned above, please update version of your GA plugin to `1.0.0-alpha.30`
