### ISSUE TITLE
using plugin-google-analytics on 1.x results in build errors

### ISSUE THREAD

**Issue by daKmoR** [vuejs/vuepress#1163]
- [x] I confirm that this is a issue rather than a question.

## Bug report

As https://vuepress.vuejs.org/config/#ga is a default option the plugin should also be installed... and according to the [default-theme readme](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/README.md) it should be... but it's not.

Installing it manually is not a problem... however when doing so you get quite some errors when building the site.

#### Version
"vuepress": "^1.0.0-alpha.30"

#### Steps to reproduce
```bash
yarn add -D @vuepress/plugin-google-analytics
```

.vuepress/config.js
```js
module.exports = {
  plugins: ['@vuepress/google-analytics'],
  ga: 'UA-00000000-1',
}
```

#### What is expected?

build without error

#### What is actually happening?

```bash
$ vuepress build docs

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
[4:53:10 AM] Compiling Client
[4:53:10 AM] Compiling Server
(node:482) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[4:53:17 AM] Compiled Server in 6s
[4:53:21 AM] Compiled Client in 10s
wait Rendering static HTML...
Rendering page: /ReferenceError: window is not defined
    at inject (server-bundle.js:4864:8)
    at server-bundle.js:5341:9
    at Array.forEach (<anonymous>)
    at createApp (server-bundle.js:5339:19)
    at module.exports.__webpack_exports__.default (server-bundle.js:5379:22)
    at new Promise (<anonymous>)
    at module.exports.__webpack_exports__.default (server-bundle.js:5378:10)
    at /mnt/c/html/open-wc/open-wc/node_modules/vue-server-renderer/build.js:8437:15
    at new Promise (<anonymous>)
    at /mnt/c/html/open-wc/open-wc/node_modules/vue-server-renderer/build.js:8399:14
    at Object.renderToString (/mnt/c/html/open-wc/open-wc/node_modules/vue-server-renderer/build.js:8575:9)
    at renderPage (/mnt/c/html/open-wc/open-wc/node_modules/@vuepress/core/lib/build.js:151:29)
    at build (/mnt/c/html/open-wc/open-wc/node_modules/@vuepress/core/lib/build.js:76:26)
Rendering page: /contact/ReferenceError: window is not defined
```

#### Other relevant information

```
$ npx https://gist.github.com/daKmoR/b509ed34576a488ea79d3ac66ccab74e
npx: installed 1 in 6.107s
$ node --version
v10.9.0

$ npm --version
6.4.1

$ cat /proc/version:
It is a WSL (Windows Subystem Linux)
Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #471-Microsoft Fri Dec 07 20:04:00 PST 2018

$ lsb_release -a:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by mAKEkr** [comment]
this issue duplicated on #1126

**Comment by daKmoR** [comment]
hmm I'm pretty sure I used the latest version of vuepress and the plug-in... but I will check again

**Comment by daKmoR** [comment]
my bad I seem to have forgotten the `@next` when installing `@vuepress/google-analytics` 🙈 

I'm sorry for the disturbance 😅 

Should we raise a different issue for the default theme as `@vuepress/plugin-google-analytics` is not installed and used by default - even though it's stated in the docs... => e.g. either add it or update/change the docs
