### ISSUE TITLE
failed to enhance style with vuetify

### ISSUE THREAD

**Issue by sammyne** [vuejs/vuepress#1169]
- [x] I confirm that this is a issue rather than a question.

## Bug report
`vuepress dev` ok, but `vuepress build` failed!

#### Version
1.0.0-alpha.30

#### Steps to reproduce

reproduction link goes as https://github.com/sammyne/sammyne.github.io

I encounter this error while building my personal github page, where I make use of a theme written myself. The theme is backed by vuetify for styling. Rendering the project locally by `vuepress dev` is fine, but collapse when I'm going to deploy it to remote by `vuepress build`.

#### What is expected?
successful build

#### What is actually happening?

error out as 

```
[8:02:30 PM] Compiling Client
[8:02:30 PM] Compiling Server
[8:02:34 PM] Compiled Server in 4s
[8:02:44 PM] Compiled Client in 14s
wait Rendering static HTML...
Rendering page: /1970/01/01/readme/error Error rendering /1970/01/01/readme/: false
undefined
/home/loccs/Workspaces/web/sammyne.github.io/node_modules/vuetify/dist/vuetify.min.css:5
*/@-webkit-keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}@keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}.black{background-color:#000!important;border-color:#000!important}.black--text{color:#000!important;caret-color:#000!important}.white{background-color:#fff!important;border-color:#fff!important}.white--text{color:#fff!important;caret-color:#fff!important}.transparent{background-color:transparent!important;border-color:transparent!important}.transparent--text{color:transparent!important;caret-color:transparent!important}.red{background-color:#f44336!important;border-color:#f44336!important}.red--text{color:#f44336!important;caret-color:#f44336!important}.red.lighten-5{background-color:#ffebee!important;border-color:#ffebee!important}.red--text.text--lighten-5{color:#ffebee!important;caret-color:#ffebee!important}.red.lighten-4{background-color

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at r (/home/loccs/Workspaces/web/sammyne.github.io/node_modules/vue-server-renderer/build.js:8365:16)
    at Object.<anonymous> (webpack:/external "vuetify/dist/vuetify.min.css":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:5994:24)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:2375:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Other relevant information

- Your OS: Fedora 29
- Node.js version: v11.1.0
- Browser version: Version 70.0.3538.102 (Official Build) (64-bit)
- Is this a global or local install?  Locally
- Which package manager did you use for the install? yarn

**Comment by moyokoo** [comment]
same error 
are you fix this problem?

**Comment by moyokoo** [comment]
@ulive could  you help us

**Comment by amystewart256** [comment]
It looks like enhanceApp.js can't correctly resolve node_modules when looking for a single file. Try this:
`import '../../node_modules/vuetify/dist/vuetify.min.css'`

instead of this:

`import 'vuetify/dist/vuetify.min.css'`

**Comment by sammyne** [comment]
It works as suggested! Thanks a lot @amystewart256 @moyokoo

**Comment by moyokoo** [comment]
thank you very much
