### ISSUE TITLE
Error: Cannot find module 'markdown-it/lib/common/html_blocks'?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [vuejs/vuepress#1188]
I want use a custom markdown, when run `npm run docs:dev`,just like this:

#### The problem happened:

```
$ npm run docs:dev

> @ docs:dev F:\hello_vuepress
> vuepress dev docs

Error: Cannot find module 'markdown-it/lib/common/html_blocks'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\hello_vuepress\node_modules\vuepress\lib\markdown\component.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ docs:dev: `vuepress dev docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ docs:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-13T08_13_23_767Z-debug.log

```

#### The log in `C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-01-13T08_13_23_767Z-debug.log` like this:

```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\develop\\nodejs\\node.exe',
1 verbose cli   'E:\\develop\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'docs:dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'predocs:dev', 'docs:dev', 'postdocs:dev' ]
5 info lifecycle @~predocs:dev: @
6 info lifecycle @~docs:dev: @
7 verbose lifecycle @~docs:dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~docs:dev: PATH: E:\develop\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\hello_vuepress\node_modules\.bin;E:\ConEmu\ConEmu\Scripts;E:\ConEmu;E:\ConEmu\ConEmu;C:\ProgramData\Oracle\Java\javapath;%JAVE_HOME%\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;E:\develop\Python2.7.13;C:\Program Files\Microsoft\Web Platform Installer\;E:\develop\php\php-7.1.3-Win32-VC14-x64;F:\develop\php\php-7.1.3-Win32-VC14-x64\ext;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;E:\develop\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\develop\nodejs\;E:\develop\flutter\bin;E:\develop\sdk;E:\Microsoft VS Code\bin\;E:\develop\Python2.7.13\;E:\develop\Python2.7.13\Scripts;E:\develop\yarn1.7.0\bin\;C:\Users\Administrator\AppData\Local\Google\Chrome\Application;E:\develop\sdk\emulator\;E:\develop\sdk\platform-tools\;E:\develop\sdk\tools\;E:\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm\;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.4-all\9br9xq1tocpiv8o6njlyu5op1\gradle-4.4\\bin\;E:\develop\sdk\tools\bin\;C:\Users\Administrator\AppData\Roaming\Pub\Cache\bin;E:\develop\DartSDK\dart-sdk\bin;E:\develop\Kotlin\kotlinc\bin;E:\develop\apache-maven-3.6.0-bin\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;E:\develop\TortoiseGit_2.4.0.2\bin;;E:\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Local\Yarn\bin
9 verbose lifecycle @~docs:dev: CWD: F:\hello_vuepress
10 silly lifecycle @~docs:dev: Args: [ '/d /s /c', 'vuepress dev docs' ]
11 silly lifecycle @~docs:dev: Returned: code: 1  signal: null
12 info lifecycle @~docs:dev: Failed to exec docs:dev script
13 verbose stack Error: @ docs:dev: `vuepress dev docs`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\develop\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (E:\develop\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd F:\hello_vuepress
16 verbose Windows_NT 6.1.7601
17 verbose argv "E:\\develop\\nodejs\\node.exe" "E:\\develop\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "docs:dev"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ docs:dev: `vuepress dev docs`
22 error Exit status 1
23 error Failed at the @ docs:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### `config.js` like this:

```
 markdown: {
    lineNumbers: true,
    anchor: { permalink: false },
    toc: { includeLevel: [1, 2, 3, 4] },
    config: md => {
      md.use(require("markdown-it-katex"));
    }
  }
```

#### `docs/README.md` like this：
```
# This is Title

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/github-markdown-css/2.2.1/github-markdown.css"/>

## Inline Math

$J \left( \theta_0, \theta_1 \right) = \frac{1}{2m}\sum\limits_{i=1}^m \left( h_{\theta}(x^{(i)})-y^{(i)} \right)^{2}$

+ Create a list by starting a line with `+`, `-`, or `*`
+ Sub-lists are made by indenting 2 spaces:
  - Marker character change forces new list start:
    * Ac tristique libero volutpat at
    + Facilisis in pretium nisl aliquet
    - Nulla volutpat aliquam velit
+ Very easy!
```

#### I had installed markdown plugin

use `yarn global add markdown-it`, and use `yarn global add markdown-it-katex`.

----

How to solve the problem？

在线等，挺急的。

**Comment by ulivz** [comment]
To ask a question that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.

**Comment by ulivz** [comment]
Please don't delete issue template or we'll close your issue. (This sentence should be visible when you created the issue. 🙂)
