### ISSUE TITLE
Header Anchors

### ISSUE THREAD

**Issue by Zyxfeng** [vuejs/vuepress#121]
The title can't begein with a Number.

**Comment by ulivz** [comment]
Thanks for reporting for that. and would you please provide the detailed step to repro? while I cannot repro for that. BTW, node version and system info should be given here.

**Comment by Zyxfeng** [comment]
When I give a title begin with number in my document, i cannot jump to that through the search input of navbar.

**Comment by Zyxfeng** [comment]
1. I setting **##1Title** in my markdown document.

2. I search **1** in the search input of default theme.

3. It will show an error in my chrome developer tools:
```
DOMException: Failed to execute 'querySelector' on 'Document': '#1greatest-common-divsior-Title' is not a valid selector.
    at scrollToPosition (webpack-internal:///../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-router/dist/vue-router.esm.js:1636:23)
    at Vue.eval (webpack-internal:///../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-router/dist/vue-router.esm.js:1579:7)
    at Array.eval (webpack-internal:///../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/vue/dist/vue.runtime.esm.js:1832:12)
    at MessagePort.flushCallbacks (webpack-internal:///../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/vue/dist/vue.runtime.esm.js:1753:14)
```
os window 10 Enterprise edition 1709
node version 8.9.0

**Comment by mdaffin** [comment]
`##1Title` is not valid markdown (some markdown parses handle it but it looks like the one vuepress uses does not) you should have a space after the last `#`: `## 1Title`

**Comment by xls12345** [comment]
First，you can go to [https://github.com/vuejs/vuepress/tree/master/packages/@vuepress/shared-utils/src/slugify.ts](url) to see the config.
And you can modify the file named slugify.js，its path in my computer is `D:\my_program\nodejs\node_global\node_modules\vuepress\node_modules\@vuepress\shared-utils\lib\slugify.js`,  find your own path, and modify it ,you can slove your problem.
