### ISSUE TITLE
Module parse failed: Unexpected token...You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by c0bra** [vuejs/vuepress#1217]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha32

#### Steps to reproduce

Affecting my repo here: https://github.com/onboardist/ui

```
git clone https://github.com/onboardist/ui onboardist && cd onboardist
npm install
npm run docs
```

#### What is expected?

Docs should build

#### What is actually happening?

Docs fail with several `Module parse failed: Unexpected token (n:n) You may need an appropriate loader to handle this file type.` error messages.

Line indicators seem to show `import` statements as being the culprit?

```
> vuepress build docs

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin vuepress-plugin- ...
[3:46:56 PM] Compiling Client
[3:46:56 PM] Compiling Server
[3:46:59 PM] Compiled Server in 3s
[3:47:06 PM] Compiled Client in 9s
(undefined) ./node_modules/@vuepress/core/lib/internal-plugins/style/client.js 2:6
Module parse failed: Unexpected token (2:6)
You may need an appropriate loader to handle this file type.
| // generated from user config
> import('@temp/style.styl');
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/1.js 1:0-107
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/app-enhancers/global-components-1.js 3:29
Module parse failed: Unexpected token (3:29)
You may need an appropriate loader to handle this file type.
| import Vue from 'vue'
|
> Vue.component("Badge", () => import("/my/project/node_modules/@vuepress/theme-default/global-components/Badge.vue"))
|
|
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js 4:0-121 11:2-4
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/internal/layout-components.js 5:20
Module parse failed: Unexpected token (5:20)
You may need an appropriate loader to handle this file type.
|  */
| export default {
>   "NotFound": () => import("/my/project/node_modules/@vuepress/theme-default/layouts/404.vue"),
|   "Layout": () => import("/my/project/node_modules/@vuepress/theme-default/layouts/Layout.vue")
| }
 @ ./node_modules/@vuepress/core/.temp/internal/routes.js 7:0-58
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/internal/page-components.js 5:22
Module parse failed: Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|  */
| export default {
>   "v-56b854bc": () => import("/my/project/docs/README.md"),
|   "v-2d763e52": () => import("/my/project/docs/components/README.md"),
|   "v-74bb66d2": () => import("/my/project/docs/components/tooltip/README.md"),
 @ ./node_modules/@vuepress/core/.temp/internal/routes.js 8:0-54
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
(undefined) ./node_modules/@vuepress/core/lib/internal-plugins/style/client.js 2:6
Module parse failed: Unexpected token (2:6)
You may need an appropriate loader to handle this file type.
| // generated from user config
> import('@temp/style.styl');
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/1.js 1:0-107
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/app-enhancers/global-components-1.js 3:29
Module parse failed: Unexpected token (3:29)
You may need an appropriate loader to handle this file type.
| import Vue from 'vue'
|
> Vue.component("Badge", () => import("/my/project/node_modules/@vuepress/theme-default/global-components/Badge.vue"))
|
|
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js 4:0-121 11:2-4
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/internal/layout-components.js 5:20
Module parse failed: Unexpected token (5:20)
You may need an appropriate loader to handle this file type.
|  */
| export default {
>   "NotFound": () => import("/my/project/node_modules/@vuepress/theme-default/layouts/404.vue"),
|   "Layout": () => import("/my/project/node_modules/@vuepress/theme-default/layouts/Layout.vue")
| }
 @ ./node_modules/@vuepress/core/.temp/internal/routes.js 7:0-58
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
(undefined) ./node_modules/@vuepress/core/.temp/internal/page-components.js 5:22
Module parse failed: Unexpected token (5:22)
You may need an appropriate loader to handle this file type.
|  */
| export default {
>   "v-56b854bc": () => import("/my/project/docs/README.md"),
|   "v-2d763e52": () => import("/my/project/docs/components/README.md"),
|   "v-74bb66d2": () => import("/my/project/docs/components/tooltip/README.md"),
 @ ./node_modules/@vuepress/core/.temp/internal/routes.js 8:0-54
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
Error: Failed to compile with errors.
    at webpack (/my/project/node_modules/@vuepress/core/lib/build.js:103:18)
    at finalCallback (/my/project/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/my/project/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/my/project/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/my/project/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/my/project/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/my/project/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/my/project/node_modules/webpack/lib/Compiler.js:220:39)
    at hooks.done.callAsync.err (/my/project/node_modules/webpack/lib/Compiler.js:236:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/my/project/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/my/project/node_modules/webpack/lib/Compiler.js:234:21)
    at hooks.afterCompile.callAsync.err (/my/project/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/my/project/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/my/project/node_modules/webpack/lib/Compiler.js:627:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/my/project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/my/project/node_modules/webpack/lib/Compilation.js:1325:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/my/project/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/my/project/node_modules/webpack/lib/Compilation.js:1316:32)
```

#### Other relevant information

- Your OS: *MacOS 10.12.6*
- Node.js version: *10*
- Is this a global or local install? *local*
- Which package manager did you use for the install? *npm*

**Comment by my9074** [comment]
+1

**Comment by ulivz** [comment]
You should know how to ask a question in a correct posture and what's a **minimal** reproduction repo. (It took me 5+ minutes to `yarn` and still not finished)

Please remove unrelated deps and create a clean repro.

**Comment by c0bra** [comment]
@ulivz The issue template literally says: _"If you are reporting a bug that can ONLY be reproduced on your repository, PLEASE provide this repo link."_

It took me 1m47s to `yarn` on a fresh checkout, so maybe check your setup next time instead of being so dismissive.

**Comment by ulivz** [comment]
So why not creating a minimal repro repo? If you try to remove your dependencies, you will find that the problem has disappeared. So this issue should not exist here.

---

To save the maintainer's time, and to exclude users who have thrown the issue here without brain thinking. I need to update the issue template 🙂
