### ISSUE TITLE
npm build: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by linbingquan** [vuejs/vuepress#1240]
I try to use `<ClientOnly />` but CMD reports: ReferenceError: window is not defined

package.json
```json
  "devDependencies": {
    "@vuepress/plugin-active-header-links": "^1.0.0-alpha.0",
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.0",
    "@vuepress/plugin-blog": "^1.0.0-alpha.0",
    "@vuepress/plugin-google-analytics": "^1.0.0-alpha.0",
    "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.0",
    "vuepress": "^1.0.0-alpha.32"
  }
```
cmd
```js
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/blog (i.e. "@vuepress/plugin-blog") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
[20:59:46] Compiling Client
[20:59:46] Compiling Server
[20:59:51] Compiled Server in 5s
[20:59:56] Compiled Client in 10s
wait Rendering static HTML...
Rendering page: /ReferenceError: window is not defined
    at inject (server-bundle.js:8075:8)
    at server-bundle.js:8577:9
    at Array.forEach (<anonymous>)
    at createApp (server-bundle.js:8575:19)
    at module.exports.__webpack_exports__.default (server-bundle.js:8616:22)
    at new Promise (<anonymous>)
    at new F (server-bundle.js:174:28)
    at module.exports.__webpack_exports__.default (server-bundle.js:8615:10)
```

**Comment by linbingquan** [comment]
Thank you for reply, I try to `npm install` reinstall dependency, `npm build` success immediately. I‘m not sure what is wrong.

 `@vuepress/plugin-google-analytics` in package-lock.json
```json
"@vuepress/plugin-google-analytics": {
    "version": "1.0.0-alpha.33"
},
```
