### ISSUE TITLE
Updating from vuepress 1.0.0-alpha.32 to 1.0.0-alpha.33 throws checkEnv 'satisfies' of undefined

### ISSUE THREAD

**Issue by Siilwyn** [vuejs/vuepress#1266]
- [x] I confirm that this is a issue rather than a question.

## Bug report
Updating from `vuepress@1.0.0-alpha.32` to `vuepress@1.0.0-alpha.33` causes the following error to be thrown when ran:
```
(node:27775) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'satisfies' of undefined
    at checkEnv (/home/siilwyn/codeground/playbook/node_modules/vuepress/lib/checkEnv.js:16:15)
    at beforeParse (/home/siilwyn/codeground/playbook/node_modules/vuepress/cli.js:15:5)
    at CLI (/home/siilwyn/codeground/playbook/node_modules/vuepress/lib/util.js:22:24)
    at Object.<anonymous> (/home/siilwyn/codeground/playbook/node_modules/vuepress/cli.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

#### Version
This seems to affect every new version above `alpha.32`.

#### Steps to reproduce

```
git clone --single-branch --branch breaking-vuepress-33 https://github.com/voorhoede/playbook.git
npm ci
npx vuepress build
```

#### What is expected?
Build to start.
#### What is actually happening?
An error is thrown.
#### Other relevant information

- Your OS: Linux
- Node.js version: 10.15.1
- Is this a global or local install?
local
- Which package manager did you use for the install?
npm

**Comment by ulivz** [comment]
It looks like npm generate the wrong dep tree, could you try `yarn`?

**Comment by Siilwyn** [comment]
Ah sorry my bad @ulivz I forgot to add the install command in the repro, updated now. I tried removing the node modules directory and lockfile followed by `npm install` to no avail. Could you try reproducing again?

This does seem to have to do something with npm, building the tree with yarn does work...

**Comment by pixlephone3** [comment]
💾

**Comment by Siilwyn** [comment]
Still not sure what is going on here but I 'fixed' it by using the yarn registry, guess this issue falls outside the scope of vuepress. I feel like the whole `checkEnv` functionality is not a good idea but that is something for another issue. :)

https://github.com/voorhoede/playbook/pull/52/commits/7f4978847b0a79fb119355331fac789054ea7dd9
