### ISSUE TITLE
[vuepress] cannot resolve plugin "@vuepress/pwa"

### ISSUE THREAD

**Issue by zhhlwd** [vuejs/vuepress#1315]
- [x] I confirm that this is a issue rather than a question.
```
[vuepress] cannot resolve plugin "@vuepress/pwa"
```
pwa don't work!
this is my theme/inde.js
```
plugins: ['@vuepress/last-updated', '@vuepress/pwa'],
```
and ./config.js
```
 head: [
    [
      'link',
      {
        rel: 'shortcut icon',
        href: '/favicon.ico'
      }
    ],
    [
      'link',
      {
        rel: 'manifest',
        href: '/manifest.json'
      }
    ],
    [
      'meta',
      {
        name: 'theme-color',
        content: '#3F51B5'
      }
    ],
    [
      'meta',
      {
        name: 'apple-mobile-web-app-capable',
        content: 'yes'
      }
    ],
    [
      'meta',
      {
        name: 'apple-mobile-web-app-status-bar-style',
        content: 'black'
      }
    ],
    [
      'link',
      {
        rel: 'apple-touch-icon',
        href: '/icons/192.png'
      }
    ],
    [
      'meta',
      {
        name: 'msapplication-TileImage',
        content: '/icons/192.png'
      }
    ],
    [
      'meta',
      {
        name: 'msapplication-TileColor',
        content: '#3F51B5'
      }
    ]
  ],
```
I have deployed to github page and you can test it
[github page](https://zhhlwd.github.io/)

```
"@vuepress/plugin-pwa": "^1.0.0-alpha.0",
"vuepress": "^1.0.0-alpha.37"
```

- Your OS: windows10
- Node.js version:  10.13.0
- Browser version:  chrome
- Is this a global or local install? local 
- Which package manager did you use for the install?npm

**Comment by ulivz** [comment]
Could you use the latest version(Same to vuepress) of `@vuepress/plugin-pwa`

**Comment by zhhlwd** [comment]
Now vuepress resolve pwa, but pwa is not installed, I used v-if to turn off vssue, 
I used Lighthouse to test this problem,

![2019-02-19_220155](https://user-images.githubusercontent.com/35592403/53021539-683ad100-3494-11e9-8470-66f3c68f33cb.png)
 I can't search for any answer, can you help me? Thank you.

**Comment by NineSwordsMonster** [comment]
I got the same issue, 
```
$ vuepress dev .
wait Extracting site metadata...
tip Apply local theme at /Volumes/Transcend/docs/sourcetree/blog/.vuepress/theme...
tip Apply theme local
warning [vuepress] cannot resolve plugin "@vuepress/active-header-links"
TypeError: Cannot read property 'multiple' of undefined
    at PluginAPI.use (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/plugin-api/index.js:94:16)
    at pluginsConfig.forEach (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/plugin-api/index.js:139:12)
    at Array.forEach (<anonymous>)
    at PluginAPI.useByPluginsConfig (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/plugin-api/index.js:138:19)
    at PluginAPI.use (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/plugin-api/index.js:105:12)
    at AppContext.applyUserPlugins (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/prepare/AppContext.js:171:22)
    at AppContext.process (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/prepare/AppContext.js:102:10)
    at prepare (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/prepare/index.js:17:20)
    at prepareServer (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/dev.js:28:32)
    at module.exports (/Users/Jarvis/.config/yarn/global/node_modules/@vuepress/core/lib/dev.js:4:40)
    at args (/Users/Jarvis/.config/yarn/global/node_modules/vuepress/lib/util.js:35:12)
    at CAC.cli.command.option.option.option.option.option.option.option.option.action (/Users/Jarvis/.config/yarn/global/node_modules/vuepress/lib/registerCoreCommands.js:34:23)
    at CAC.runMatchedCommand (/Users/Jarvis/.config/yarn/global/node_modules/cac/dist/index.js:787:38)
    at CAC.parse (/Users/Jarvis/.config/yarn/global/node_modules/cac/dist/index.js:707:18)
    at CLI (/Users/Jarvis/.config/yarn/global/node_modules/vuepress/lib/util.js:23:7)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
As I try to change plugin config from babel style to object style, it works.
I have no idea about it.

**Comment by ulivz** [comment]
Please do not report issues at a closed issue or no one would help you.

**Comment by bungder** [comment]
> Please do not report issues at a closed issue or no one would help you.

Why did you close this issue while it was never resolved?
