### ISSUE TITLE
Build fails if we have `{{ }}` in the .md file 

### ISSUE THREAD

**Issue by shashank-k** [vuejs/vuepress#1325]
- [x ] I confirm that this is a issue rather than a question.

## Bug report

Build fails if we have `{{ }}` in the .md file with the following logs

```
{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"8ffac054-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./docs/XXXXXX.md?vue&type=template&id=2c823e82&)
```

#### Steps to reproduce

Add `{{ }}` inside a .md file and start the build process. 

#### What is expected?

To parse properly

#### What is actually happening?

erroring out 

#### Other relevant information

NA

- Your OS:  CI provided by Gitlab
- Node.js version:  NA
- Browser version:  NA
- Is this a global or local install? working with gitlab
- Which package manager did you use for the install? npm

**Comment by Shigma** [comment]
Sorry, I cannot reproduce your issue. Can you provide a reproduction repo (e.g. [vuepress-1306](https://github.com/meteorlxy/vuepress-1306))?

**Comment by shashank-k** [comment]
The test [repo](https://gitlab.com/shashankk/test.git)

The below is the entire build log.

```Running with gitlab-runner 11.8.0-rc1 (7a7b8375)
  on docker-auto-scale 0277ea0f
Using Docker executor with image node:latest ...
Pulling docker image node:latest ...
Using docker image sha256:c63e58f0a7b2426431e2c8cd93d52392931e1993587165a91920b472b14d7f66 for node:latest ...
Running on runner-0277ea0f-project-10972900-concurrent-0 via runner-0277ea0f-srm-1550818902-036b9b6e...
Cloning repository...
Cloning into '/builds/shashankk/test'...
Checking out b8f69875 as master...
Skipping Git submodules setup
Checking cache for default...
FATAL: file does not exist                         
Failed to extract cache
$ npm install
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1355 packages from 625 contributors and audited 11930 packages in 33.301s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm run docs:build

> test@1.0.0 docs:build /builds/shashankk/test
> vuepress build docs


 WAIT  Extracting site metadata...
[7:03:53 AM] Compiling Client
[7:03:53 AM] Compiling Server
[7:04:06 AM] Compiled Server in 13s
[7:04:06 AM] Compiled Client in 13s
(undefined) ./docs/test.md?vue&type=template&id=d58869a2& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"0dd9ad42-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./docs/test.md?vue&type=template&id=d58869a2&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:249)
    at Parser.pp$4.raise (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseExprAtom (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2196:10)
    at Parser.<anonymous> (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:6003:24)
    at Parser.parseExprAtom (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$2.parseSpread (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1653:24)
    at Parser.pp$3.parseExprList (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2659:20)
    at Parser.pp$3.parseSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
 @ ./docs/test.md?vue&type=template&id=d58869a2& 1:0-443 1:0-443
 @ ./docs/test.md
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js
(undefined) ./docs/test.md?vue&type=template&id=d58869a2& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"8ffac054-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./docs/test.md?vue&type=template&id=d58869a2&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:256)
    at Parser.pp$4.raise (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseExprAtom (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2196:10)
    at Parser.<anonymous> (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:6003:24)
    at Parser.parseExprAtom (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$2.parseSpread (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1653:24)
    at Parser.pp$3.parseExprList (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2659:20)
    at Parser.pp$3.parseSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/builds/shashankk/test/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
 @ ./docs/test.md?vue&type=template&id=d58869a2& 1:0-443 1:0-443
 @ ./docs/test.md
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/serverEntry.js
 @ multi ./node_modules/vuepress/lib/app/serverEntry.js
Error: Failed to compile with errors.
    at webpack (/builds/shashankk/test/node_modules/vuepress/lib/build.js:108:18)
    at finalCallback (/builds/shashankk/test/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/builds/shashankk/test/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/builds/shashankk/test/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/builds/shashankk/test/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/builds/shashankk/test/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/builds/shashankk/test/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/builds/shashankk/test/node_modules/webpack/lib/Compiler.js:220:39)
    at hooks.done.callAsync.err (/builds/shashankk/test/node_modules/webpack/lib/Compiler.js:236:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/shashankk/test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/shashankk/test/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/builds/shashankk/test/node_modules/webpack/lib/Compiler.js:234:21)
    at hooks.afterCompile.callAsync.err (/builds/shashankk/test/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/shashankk/test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/shashankk/test/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/builds/shashankk/test/node_modules/webpack/lib/Compiler.js:627:30)
Creating cache default...
node_modules/: found 22408 matching files          
Uploading cache.zip to https://storage.googleapis.com/gitlab-com-runners-cache/project/10972900/default 
Created cache
Uploading artifacts...
WARNING: public: no matching files                 
ERROR: No files to upload                          
Job succeeded
```

**Comment by Shigma** [comment]
Have a look at these documentation:
- https://vuepress.vuejs.org/guide/using-vue.html#templating
- https://vuejs.org/v2/guide/syntax.html#Text

Mustaches are interpreted as javascript expressions, so your `{{ ... }}` is wrong in syntax.

**Comment by Shigma** [comment]
In such cases, you can use `<code v-text="'{{ ... }}'"/>` instead.
