### ISSUE TITLE
VuePress build error

### ISSUE THREAD

**Issue by luhavis** [vuejs/vuepress#133]
`$ vuepress build`

```
Rendering static HTML...
Rendering page: /Error rendering /:
TypeError: enhanceApp_default(...) is not a function
    at createApp (server-bundle.js:2745:23)
    at module.exports.__webpack_exports__.default (server-bundle.js:2765:13)
    at new Promise (<anonymous>)
    at module.exports.__webpack_exports__.default (server-bundle.js:2764:110)
    at /home/luhavis/.config/yarn/global/node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at /home/luhavis/.config/yarn/global/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/luhavis/.config/yarn/global/node_modules/vue-server-renderer/build.js:8564:9)
    at renderPage (/home/luhavis/.config/yarn/global/node_modules/vuepress/lib/build.js:143:29)
    at build (/home/luhavis/.config/yarn/global/node_modules/vuepress/lib/build.js:66:11)
    at  <anonymous>
```
How to Fix it?

**Comment by fjc0k** [comment]
Do you use `enhanceApp.js` ?

If yes, ensure it `export default` a function.
