### ISSUE TITLE
vuepress build docs Error For Leaflet

### ISSUE THREAD

**Issue by winbug** [vuejs/vuepress#1408]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
添加Leaflet后,build出错

#### Version
Vuepress: /1.0.0-alpha.27 linux-x64 node-v11.0.0
Leaflet: ^1.4.0

#### Steps to reproduce
```
yarn add leaflet
```

vue文件的script中添加
```
import  'leaflet/dist/leaflet.css'
import  L from 'leaflet'
.
.
.
methods:{
L.map( 'map1', { center: L.latLng( 35.6825, 139.752778 ), zoom: 15 } ).addLayer(
            L.tileLayer( 'http://{s}.tile.osm.org/{z}/{x}/{y}.png' )
        )
}
```

yarn docs:dev 运行没有问题。
yarn docs:build 出现以下错误

```
Rendering static HTML...
Rendering page: /Error rendering /:
Error: render function or template not defined in component: HomeLayout
    at normalizeRender (/var/www/html/git/vuepress-netlify-cms/node_modules/vue-server-renderer/build.js:7396:13)
    at renderComponentInner (/var/www/html/git/vuepress-netlify-cms/node_modules/vue-server-renderer/build.js:7520:3)
    at renderComponent (/var/www/html/git/vuepress-netlify-cms/node_modules/vue-server-renderer/build.js:7491:5)
    at resolve (/var/www/html/git/vuepress-netlify-cms/node_modules/vue-server-renderer/build.js:7552:9)
33.server-bundle.js:494
    }(window, function (t, e) {
      ^

ReferenceError: window is not defined
    at Timeout._onTimeout (33.server-bundle.js:494:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Other relevant information

- Your OS: Ubuntu 18.10
- Node.js version:  11.0.0
- Browser version: Chrome v72
- Is this a global or local install? global install
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled?

**Comment by Shigma** [comment]
https://v1.vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

leaflet 依赖于浏览器环境运行，这是 build 下不允许的。尝试使用上面文档中的解决方案，或许能够解决您的问题。

**Comment by winbug** [comment]
按照链接里的方法，解决了。非常感谢
```
mounted() {
    import('leaflet').then(module => {
      L.map( 'map1', { center: L.latLng( 35.6825, 139.752778 ), zoom: 15 } ).addLayer(
            L.tileLayer( 'http://{s}.tile.osm.org/{z}/{x}/{y}.png' )
        )
    })    
  }
```

**Comment by qianzhangsheng** [comment]
cesium也出现这个问题
