### ISSUE TITLE
Markdown rendering error with inline code block

### ISSUE THREAD

**Issue by saltymouse** [vuejs/vuepress#1688]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
1. `mkdir vuepress-test && cd $_`
2. ``echo '# Inline Code Test \n\nHere is an inline `{{ code() }}` block' > README.md``
3. `npx vuepress build`
4. Error rendering... (see below)

#### What is expected?

Render the content of README.md as the home index as such:
```
<h1>Inline Code Test</h1>
<p>Here is an inline <code>{{ code() }}</code> block</p>
```

#### What is actually happening?

It seems like the error arises from a problem with the specific inline code block of `` `{{ () }}` ``.

Rendering Error
```
✔ Client
  Compiled successfully in 9.05s

✔ Server
  Compiled successfully in 4.54s

wait Rendering static HTML...
Rendering page: /[Vue warn]: Error in render: "TypeError: _vm.code is not a function"

found in

---> <V1542ccb3>
       <Content>
         <Page>
           <Anonymous>
             <Anonymous>
               <Root>
error Error rendering /: false
undefined
TypeError: _vm.code is not a function
    at Proxy.render (README.md?34e1:1:302)
    at VueComponent.Vue._render (/Users/salty/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
    at resolve (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8400:27)
    at waitForServerPrefetch (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at renderNode (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at resolve (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8406:5)
    at waitForServerPrefetch (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at RenderContext.renderNode (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at RenderContext.next (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:2598:23)
    at cachedWrite (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:2451:9)
    at renderStringNode$1 (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8486:5)
    at RenderContext.renderNode (/Users/salty/.config/yarn/global/node_modules/vue-server-renderer/build.dev.js:8277:5)
```

#### Other relevant information

- Errors only appear during `vuepress build`. These errors are silent during `dev` as outlined in #1549
  - `{{ () }}` → Build Error
- Double curley-brace pairs in markdown paragraphs are stripped from the HTML output (yet do not error even in `vuepress build`).
  - `...test {{ }} inline...` → `<p>...test inline...</p>`
- Single curley-brace pairs in paragraphs are successfully rendered to HTML
  - `...test { } inline...` → `<p>...test { } inline...</p>`

- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  Binaries:
    Node: 10.16.0 - ~/.npm-global/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ulivz** [comment]
See: https://v1.vuepress.vuejs.org/guide/using-vue.html#escaping

````
::: v-pre
{{ code() }}
:::
````
