### ISSUE TITLE
As long as the following contents are written in the markdown file, vuepress will not compile and the following errors will occur. I haven't found the reason yet.

### ISSUE THREAD

**Issue by qingfengfenga** [vuejs/vuepress#1693]
Markwond file content
`# 18.9 网络和网页应用

## 模板：

制作、解析并使模板生效：

```go
var strTempl = template.Must(template.New("TName"),Parse(strTemplateHTML))
```

在网页应用中使用HTML过滤器过滤HTML特殊字符：

`{{html .}}` 或者通过一个字段 `FieldName {{ .FieldName|html }}`

使用缓存模板（参考[章节15.7](15.7.md)）

## 链接

- [目录](directory.md)
- 上一节：[协程（goroutine）与通信（channel）](18.8.md)- 下一节：[其他](18.10.md)`
run`npm run docs：build`Error prompt
`
[wyp@rancher-master vuepress]$ npm run docs:build

> @ docs:build /home/vuepress
> vuepress build docs

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...

● Client █████████████████████████ chunk asset optimi
zation (92%) OptimizeCssAssetsWebpackPlugin 
 

✖ Server
  Compiled with some errors in 13.89s

✖ Client
  Compiled with some errors in 18.65s

✖ Server
  Compiled with some errors in 13.89s

(undefined) ./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"1e06a534-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:1762)
    at Parser.pp$4.raise (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseIdent (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2712:10)
    at Parser.pp$3.parseSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2067:68)
    at Parser.pp$3.parseExprSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parseExprList (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
 @ ./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548& 1:0-469 1:0-469
 @ ./docs/the-way-to-go/ebook/18.9.md
 @ ./node_modules/@vuepress/core/.temp/internal/page-components.js
 @ ./node_modules/@vuepress/core/lib/client/util.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) ./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"6645532a-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:1762)
    at Parser.pp$4.raise (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseIdent (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2712:10)
    at Parser.pp$3.parseSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2067:68)
    at Parser.pp$3.parseExprSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parseExprList (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/vuepress/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
 @ ./docs/the-way-to-go/ebook/18.9.md?vue&type=template&id=f67ac548& 1:0-469 1:0-469
 @ ./docs/the-way-to-go/ebook/18.9.md
 @ ./node_modules/@vuepress/core/.temp/internal/page-components.js
 @ ./node_modules/@vuepress/core/lib/client/util.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at webpack (/home/vuepress/node_modules/@vuepress/core/lib/node/build/index.js:186:16)
    at finalCallback (/home/vuepress/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/home/vuepress/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/home/vuepress/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/vuepress/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/home/vuepress/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/home/vuepress/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/home/vuepress/node_modules/webpack/lib/Compiler.js:220:39)
    at hooks.done.callAsync.err (/home/vuepress/node_modules/webpack/lib/Compiler.js:236:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/vuepress/node_modules/webpack/lib/Compiler.js:234:21)
    at hooks.afterCompile.callAsync.err (/home/vuepress/node_modules/webpack/lib/Compiler.js:631:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/home/vuepress/node_modules/webpack/lib/Compiler.js:628:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wyp/.npm/_logs/2019-07-10T09_19_40_036Z-debug.log
[wyp@rancher-master vuepress]$ 
`
Changing the name of the file can not compile properly, but as long as you delete the contents of the file and replace them with other contents, you can compile properly. It should be that vuepress can not correctly recognize the characters of these contents. Specifically, which I am still testing

**Comment by ulivz** [comment]
See: https://v1.vuepress.vuejs.org/guide/using-vue.html#escaping
