### ISSUE TITLE
Error: Cannot find module './Mime'

### ISSUE THREAD

**Issue by zeke** [vuejs/vuepress#189]
Following the instructions on https://vuepress.vuejs.org/#as-easy-as-1-2-3, I see this:

```
$ yarn global add vuepress
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.6.0" while you're on "0.27.5".
info To upgrade, run the following command:
$ npm upgrade --global yarn
success Installed "vuepress@0.7.1" with binaries:
      - vuepress
warning No license field
Done in 14.12s.
```

```
$ echo '# Hello VuePress' > README.md
```

```
$ vuepress dev
Error: Cannot find module './Mime'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/z/.config/yarn/global/node_modules/mime/index.js:3:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

```
$ node -v
v8.10.0
```

**Comment by yyx990803** [comment]
Closing due to inactivity. Feel free to reopen if you still run into this with latest version of Yarn.

**Comment by zeke** [comment]
Upgrading yarn fixed it. Thanks!
