### ISSUE TITLE
Reports "success!" even if all docs fail to render 

### ISSUE THREAD

**Issue by bep** [vuejs/vuepress#19]
I just installed and tested Vuepress with 1000 simple Markdown files in a folder:

```bash
▶ time vuepress build .
````

After 2 minutes it starts to spit errors of the kind below.  The main point of this issue, however, is the "Success!" part.

```bash
/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)
Error rendering /README998.html:
TypeError: G(...) is not a function or its return value is not iterable
    at G.t.map.t (server-bundle.js:3:355591)
    at Array.map (<anonymous>)
    at G (server-bundle.js:3:355484)
    at render (server-bundle.js:3:356015)
    at s.render (server-bundle.js:1:1550)
    at createFunctionalComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:3:358322
    at VueComponent.renderList [as _l] (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.<anonymous> (server-bundle.js:3:358105)
    at VueComponent.Vue._render (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)
Error rendering /README999.html:
TypeError: G(...) is not a function or its return value is not iterable
    at G.t.map.t (server-bundle.js:3:355591)
    at Array.map (<anonymous>)
    at G (server-bundle.js:3:355484)
    at render (server-bundle.js:3:356015)
    at s.render (server-bundle.js:1:1550)
    at createFunctionalComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:3:358322
    at VueComponent.renderList [as _l] (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.<anonymous> (server-bundle.js:3:358105)
    at VueComponent.Vue._render (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)

Success! Generated static files in .vuepress/dist.
vuepress build .   133.71s  user 5.26s system 170% cpu 1:21.70 total
```

The Markdown used in test:

```markdown
# Qua et pennis in sim inmitem

## Lumen exspectato est fecisse enim pericula totidemque

Lorem markdownum mortis caede *intima animi sinus* vestes iustissime, finita.
**Torus motaque timidumque** sacerdos dea arida deos vix tamquam, **per**.
Raptor et Vulcani pisce; ullus rabie sanguine memoresque supremumque clamat.
Quaeque satis; virum iam Taurusque intrat Phoronidos regina ferant, altis!

Nutu aspera totidem blanditias regimen Isthmo est illa damnatus! Adhuc crimen
flagratque remorata labores servaturis pius.
[Refertque](http://vulnerequoque.org/) suo fixa confessam leonis perlucida
vultus Tritonia deos, vidistis Saturnius Silenus neve est et perierunt.

- Mansit nymphe discussit superest terga contendere laceras
- Erat anus
- Ades caesa petunt crudelis cecidisse Eleis me
- Sibi recepta etiamnum
- Potiere virginis
- Hoc sine magna aera omnis

## Manus columbae perfudit coniuge cornum Medusae vitiato

Arcana ille herbae idque, praebuit mensis, quisquis misceri *error*, qui.
Equumque opaca, positoque violas perdiderat auditi tempore caespite mutatas.
Adhuc **illius deficiunt** infirmos verbis. Satiantur versa, dum verba humo nec
Perseus ibant demere [ablata gelidi](http://puellae.org/creatis.php) est, in
aperire iubent tum! Huius evehor terram gemitumque nullis te laetus **solebat
vultibus** certamine translata tamen.

Huic inpositum strata percepto utque: undas omnia, perosus demi namque. Misit
digiti gaudia cepit quadriiugo varias. Aeratas de corpore quantusque villis
spectansque ille ipsius soror.

Erat erit et inde esse praesens et recepto [modo
peperit](http://pyreneusdiramque.org/) iram: sub sub viscata sua. Ac serta ne
maestis gaudia nemorisque Theti et ille rex? Revincta Gorgoneis terram virgo
siqua omnibus; peto parentum, patrem **contortam facies adsumit**: ambo tanta.
Et damnare crematisregia sine ululare Alcyonen tabellas litora hirsutaque
confinia requiem satyri adhuc sceleris!

- Carica hastam properas fecerat
- Bellator murice sed populus dextra pulvereamque quove
- Ad amor nautae
- Ita medios in iussis vocant cubitoque quae
- Adcommodat consurgit tellus putaret fugio intremuere dederis
- Soporis huc ipsum velis estque dixit haec

Nisi relictum Stygiam contra mihi **unda decerpta aures** radix, qui et. Tu
Cytherea canam sorsque obstitit. Que *quid*. Deos vastum depulerant!
```

**Comment by ulivz** [comment]
Would you please give us a repo to let us repro that? thanks.

**Comment by bep** [comment]
1. Create a folder with a `README.md` with the above markdown.
2. Run `for i in {2..1000}; do cp README.md README$i.md; done`
3. Run `vuepress build .`

**Comment by yyx990803** [comment]
I see where you're coming from, but performance isn't a core focus of VuePress. The design is largely limited by webpack (having 1000 pages means 1000 Vue components being compiled via webpack and minified) and looks like it runs out of memory at some point with 1000 pages.

Tested that we can handle ~300 pages in around 40s, and there are probably quite a few low hanging fruits to improve perf as the current implementation essentially didn't take build perf into consideration at all.

**Comment by bep** [comment]
As an added note, I get the same error with 100 pages:

````
renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)
Error rendering /README98.html:
TypeError: G(...) is not a function or its return value is not iterable
    at G.t.map.t (server-bundle.js:3:49590)
    at Array.map (<anonymous>)
    at G (server-bundle.js:3:49483)
    at render (server-bundle.js:3:50014)
    at l.render (server-bundle.js:1:1549)
    at createFunctionalComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:3:52321
    at VueComponent.renderList [as _l] (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.<anonymous> (server-bundle.js:3:52104)
    at VueComponent.Vue._render (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)
Error rendering /README99.html:
TypeError: G(...) is not a function or its return value is not iterable
    at G.t.map.t (server-bundle.js:3:49590)
    at Array.map (<anonymous>)
    at G (server-bundle.js:3:49483)
    at render (server-bundle.js:3:50014)
    at l.render (server-bundle.js:1:1549)
    at createFunctionalComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:3:52321
    at VueComponent.renderList [as _l] (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.<anonymous> (server-bundle.js:3:52104)
    at VueComponent.Vue._render (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7491:5)

Success! Generated static files in .vuepress/dist.
vuepress build .   26.12s  user 1.85s system 173% cpu 16.098 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                279228 MB
page faults from disk:     3330
other page faults:         222319
```

**Comment by yyx990803** [comment]
Hmm, I was not able to reproduce the behavior even with 1000 pages. It simply ran out of memory and worked properly with 300 pages.
