### ISSUE TITLE
After upgrading to  Vuepress 1.1.0 getting Error: Content placeholder not found in template

### ISSUE THREAD

**Issue by jpvajda** [vuejs/vuepress#1905]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I've gone ahead an upgraded my vuepress site from `0.14.8` to`1.1.0`. I've also upgrade the default theme from `1.0.0-alpha.0` to `1.1.0` However when attempting to build the site I am getting the  following error:

```
Error: Content placeholder not found in template.
    at parseTemplate (/Users/x/Documents/GitLab/docs/node_modules/vue-server-renderer/build.dev.js:8773:11)
    at new TemplateRenderer (/Users/x/Documents/GitLab/docs/node_modules/vue-server-renderer/build.dev.js:8866:9)
    at createRenderer (/Users/x/Documents/GitLab/docs/node_modules/vue-server-renderer/build.dev.js:9131:26)
    at createRenderer$1 (/Users/x/Documents/GitLab/docs/node_modules/vue-server-renderer/build.dev.js:9589:10)
    at createBundleRenderer (/Users/x/Documents/GitLab/docs/node_modules/vue-server-renderer/build.dev.js:9506:20)
    at Build.render (/Users/x/Documents/GitLab/docs/node_modules/@vuepress/core/lib/node/build/index.js:71:21)
error Command failed with exit code 1.
```

I've gone ahead and read all the documentation on this upgrade to 1.0+  and can't seem to find out why this occurring.  I can't  actually provide  a reproduction of the repo due to internal security rules at my company but here are the package.json file and config.js file
```
{
  "name": "documentation",
  "version": "1.0.0",
  "description": "Developer Documentation",
  "main": "index.js",
  "author": "kratos",
  "license": "MIT",
  "private": true,
  "scripts": {
    "start": "vuepress dev docs",
    "build": "vuepress build docs"
  },
  "dependencies": {
    "@vuepress/plugin-active-header-links": "^1.0.0-alpha.0",
    "@vuepress/plugin-search": "^1.0.0-alpha.0",
    "@vuepress/theme-default": "^1.1.0",
    "caniuse-db": "^1.0.30000925",
    "cypress": "^3.2.0",
    "docsearch.js": "^2.6.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2"
  },
  "devDependencies": {
    "@hawkeyesec/scanner-cli": "^1.4.0",
    "vuepress": "1.1.0"
  }
}
```

```
module.exports = {
  title: 'x Docs',
  description: 'x Product Documentation',
  base: '/',
  dest: 'public',
  head: [
     ['link', { rel: 'icon', href: '/favicon.png' }],
   ],
  themeConfig: {
        search: true,
        searchMaxSuggestions: 10,
        repo: 'https://gitlab.com/x/docs/',
        repoLabel: 'Gitlab',
        editLinks: true,
        editLinkText: 'Edit this page on Gitlab',
        sidebar: 'auto',
        sidebarDepth: 5,
        displayAllHeaders: true,
        nav: [
                { text: 'Home', link: '/' },
                { text: 'Documentation', link: '/documentation/' },
                { text: 'Support', link: '/support/' },
                { text: 'ChangeLog', link: 'https://gitlab.com/x/docs/blob/master/CHANGELOG.md' },
            ],
      },
};



```

#### Steps to reproduce

1. upgrade a vuepress installation from `0.14.8` to`1.1.0`.  
2. upgrade the default theme from `1.0.0-alpha.0` to `1.1.0` 
3. run yarn build 

#### What is expected?

site should build with no errors. 

#### What is actually happening?

errors are generated.  specifically: `Error: Content placeholder not found in template.`

#### Other relevant information

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    @vuepress/core:  1.1.0
    @vuepress/theme-default: ^1.1.0 => 1.1.0
    vuepress: 1.1.0 => 1.1.0
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by jpvajda** [comment]
I did an upgrade from 1.04 to 1.1.0 to see if that would resolve the issue, and it did not.

**Comment by kefranabg** [comment]
Is it working if you do a migration from `0.14.8` to `1.0.4` ?

**Comment by jpvajda** [comment]
@kefranabg I had the  exact same problem with the 1.0.4 version.

**Comment by ulivz** [comment]
@jpvajda Please create a minimal reproduction repo, thanks.

**Comment by jpvajda** [comment]
@ulivz will do. once i have the repo reproduced I'll link to it in this issue. Thank you!

**Comment by jpvajda** [comment]
@ulivz here is the public repo reproduced. I stripped out a lot of content specific files as well as the /dist folder.   https://gitlab.com/johnpvajda/vuepress-support

**Comment by jpvajda** [comment]
I figured out how to fix this, so it can be closed, but here is what I needed to do, just remove the template directory from the project. `rm -rf docs/.vuepress/templates`
