### ISSUE TITLE
my file is named of !!.md, vuepress build error 

### ISSUE THREAD

**Issue by HackettYu** [vuejs/vuepress#1937]
- [ X ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```bash
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
i Compiling Client
i Compiling Server
Language does not exist math
Language does not exist javv
Language does not exist txt
Language does not exist txt
Language does not exist word
Language does not exist text
Language does not exist url
Language does not exist api
Language does not exist maven
Language does not exist maven
Language does not exist jsp
Language does not exist jsp
Language does not exist jsp
Language does not exist txt
Language does not exist text
Language does not exist text
Language does not exist txt
Language does not exist text
Language does not exist text
Language does not exist text
Language does not exist text
Language does not exist text
√ Server: Compiled with some errors in 33.08s
√ Client: Compiled with some errors in 44.07s
(undefined) C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js
Module not found: Error: Can't resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
  Parsed request is a directory
  using description file: C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\package.json (relative path: ./.temp/internal)
    using description file: F:\project\note\package.json (relative path: ./docs/command/cmd)
      as directory
        existing directory
          using path: F:\project\note\docs\command\cmd\index
            using description file: F:\project\note\package.json (relative path: ./docs/command/cmd/index)
              no extension
                F:\project\note\docs\command\cmd\index doesn't exist
              .js
                F:\project\note\docs\command\cmd\index.js doesn't exist
              .json
                F:\project\note\docs\command\cmd\index.json doesn't exist
[F:\project\note\docs\command\cmd\index]
[F:\project\note\docs\command\cmd\index.js]
[F:\project\note\docs\command\cmd\index.json]
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js 16:22-76
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/util.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/app.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js
Module not found: Error: Can't resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
  Parsed request is a directory
  using description file: C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\package.json (relative path: ./.temp/internal)
    using description file: F:\project\note\package.json (relative path: ./docs/command/cmd)
      as directory
        existing directory
          using path: F:\project\note\docs\command\cmd\index
            using description file: F:\project\note\package.json (relative path: ./docs/command/cmd/index)
              no extension
                F:\project\note\docs\command\cmd\index doesn't exist
              .js
                F:\project\note\docs\command\cmd\index.js doesn't exist
              .json
                F:\project\note\docs\command\cmd\index.json doesn't exist
[F:\project\note\docs\command\cmd\index]
[F:\project\note\docs\command\cmd\index.js]
[F:\project\note\docs\command\cmd\index.json]
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js 16:22-76
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/util.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/app.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at webpack (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\lib\node\build\index.js:186:16)
    at finalCallback (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at runWithDependencies.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:277:6)
    at done (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\neo-async\async.js:2931:13)
    at runCompilers (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:188:7)
    at compiler.run (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:270:7)
    at finalCallback (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:257:39)
    at hooks.done.callAsync.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:678:31)

Hackett@Hackett MINGW64 /f/project/note (master)
$ vuepress build
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
i Compiling Client
i Compiling Server
√ Server: Compiled with some errors in 14.19s
√ Client: Compiled with some errors in 28.34s
(undefined) C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js
Module not found: Error: Can't resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
  Parsed request is a directory
  using description file: C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\package.json (relative path: ./.temp/internal)
    using description file: F:\project\note\package.json (relative path: ./docs/command/cmd)
      as directory
        existing directory
          using path: F:\project\note\docs\command\cmd\index
            using description file: F:\project\note\package.json (relative path: ./docs/command/cmd/index)
              no extension
                F:\project\note\docs\command\cmd\index doesn't exist
              .js
                F:\project\note\docs\command\cmd\index.js doesn't exist
              .json
                F:\project\note\docs\command\cmd\index.json doesn't exist
[F:\project\note\docs\command\cmd\index]
[F:\project\note\docs\command\cmd\index.js]
[F:\project\note\docs\command\cmd\index.json]
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js 16:22-76
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/util.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/app.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js
Module not found: Error: Can't resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
resolve 'F:\project\note\docs\command\cmd\' in 'C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\.temp\internal'
  Parsed request is a directory
  using description file: C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\package.json (relative path: ./.temp/internal)
    using description file: F:\project\note\package.json (relative path: ./docs/command/cmd)
      as directory
        existing directory
          using path: F:\project\note\docs\command\cmd\index
            using description file: F:\project\note\package.json (relative path: ./docs/command/cmd/index)
              no extension
                F:\project\note\docs\command\cmd\index doesn't exist
              .js
                F:\project\note\docs\command\cmd\index.js doesn't exist
              .json
                F:\project\note\docs\command\cmd\index.json doesn't exist
[F:\project\note\docs\command\cmd\index]
[F:\project\note\docs\command\cmd\index.js]
[F:\project\note\docs\command\cmd\index.json]
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/.temp/internal/page-components.js 16:22-76
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/util.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/app.js
 @ C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi C:/Users/hasee/AppData/Local/Yarn/Data/global/node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at webpack (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\lib\node\build\index.js:186:16)
    at finalCallback (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at runWithDependencies.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:277:6)
    at done (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\neo-async\async.js:2931:13)
    at runCompilers (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:188:7)
    at compiler.run (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\MultiCompiler.js:270:7)
    at finalCallback (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:257:39)
    at hooks.done.callAsync.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\Users\hasee\AppData\Local\Yarn\Data\global\node_modules\webpack\lib\Compiler.js:678:31)
```

## version

```bash
$ vuepress -version
cli.js/1.1.0 win32-x64 node-v10.15.3
$ npm -version
6.11.3
$ yarn -version
1.15.2
```

## solution

change to `fuck.md`

**Comment by Mister-Hope** [comment]
hhhhhh

**Comment by lgg** [comment]
got this issue too...
