### ISSUE TITLE
Dev works, build gets stuck at undef. window

### ISSUE THREAD

**Issue by ellipticcurv3** [vuejs/vuepress#2065]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

The error occurs at https://github.com/ellipticcurv3/www/commit/fcd4ee6435cf6fee2e9df71d3d162133bf9b9a5c

```sh
cd $(mktemp -d)
git clone --depth 5 git@github.com:ellipticcurv3/www.git .
git checkout fcd4ee6435cf6fee2e9df71d3d162133bf9b9a5c
npm i
npm run build    # which does `npx vuepress build src`
```

#### What is expected?

I expect my site to build, but it fails at the stage of rendering the static HTML.

#### What is actually happening?

I seem to get the following message:

```
Rendering page: [...] [Vue warn]: Failed to resolve async component: () => Promise.all(/* import() */[__webpack_require__.e(3), __webpack_require__.e(2)]).then(__webpack_require__.bind(null, 389))
Reason: ReferenceError: window is not defined
[...]
undefined
Error: render function or template not defined in component: Layout
    at normalizeRender (/tmp/tmp.CFeBD2iQ5t/node_modules/vue-server-renderer/build.dev.js:8247:13)
    at renderComponentInner (/tmp/tmp.CFeBD2iQ5t/node_modules/vue-server-renderer/build.dev.js:8397:3)
    at renderComponent (/tmp/tmp.CFeBD2iQ5t/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at resolve (/tmp/tmp.CFeBD2iQ5t/node_modules/vue-server-renderer/build.dev.js:8436:9)
```

Running the dev server works fine, so it should be some failure in the SSR script. Some code tries to access `window`, which, to my understanding, is only available to browsers, but I can't find where `window` is used. Tried to disable plugins ("moment", for example), remove Vue components (HumanReadableDate, `vue-inline-svg` etc.). I even tried to add a `render() { ... }` to `Layout.vue`, and do it on a global installation of VuePress. But that all didn't work.

Where can I find the problematic code and how can I fix it?

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
  npmPackages:
    @vuepress/core:  1.2.0 
    @vuepress/theme-default:  1.2.0 
    vuepress: ^1.2.0 => 1.2.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ellipticcurv3** [comment]
Fixed in https://github.com/ellipticcurv3/www/commit/4c5d2c77fa6af081d7da935fce62833ff87dd140. It was caused by an unnecessary import of `foundation-sites` (the javascript bundle), which obvs. caused a call to the `window` object, while it is not present in the node environment.
