### ISSUE TITLE
vuepress installation success, but faild to run vuepress dev

### ISSUE THREAD

**Issue by artmarydotir** [vuejs/vuepress#2122]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- yarn global add vuepress # OR npm install -g vuepress
- mkdir vuepress-starter && cd vuepress-starter
- echo '# Hello VuePress' > README.md
- vuepress dev

#### Version
vuepress: 1.2.0
OS: Ubuntu 18.04

#### What is expected?
vuepress works

#### What is actually happening?
```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/.temp'
    at Object.mkdirSync (fs.js:839:3)
    at Object.mkdirsSync (/usr/local/lib/node_modules/vuepress/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at createTemp (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/createTemp.js:21:8)
    at new App (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/App.js:48:37)
    at createApp (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/index.js:9:10)
    at dev (/usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/index.js:13:15)
    at /usr/local/lib/node_modules/vuepress/lib/util.js:35:12
    at CAC.<anonymous> (/usr/local/lib/node_modules/vuepress/lib/registerCoreCommands.js:38:23)
    at CAC.runMatchedCommand (/usr/local/lib/node_modules/vuepress/node_modules/cac/dist/index.js:700:38)
    at CAC.parse (/usr/local/lib/node_modules/vuepress/node_modules/cac/dist/index.js:620:18)
    at CLI (/usr/local/lib/node_modules/vuepress/lib/util.js:23:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
#### Other relevant information

After success installation with yarn or npm 
when i run vuepress dev
i got the error,
why vuepress want to create folder in this path?
and why im getting this error?

**Comment by CaiPeng1989** [comment]
[temp](https://vuepress.vuejs.org/config/#temp)
> - Type: string
> - Default: /path/to/@vuepress/core/.temp
Specify the temporary directory for client.

**Comment by meteorlxy** [comment]
@CaiPeng1989 has provided the valid solution.

We may need to refine the documentation about this.

**Comment by f3ltron** [comment]
Please consider to install vuepress on your project package. We should avoid using vuepress globally. I think the doc was not update on this part.

Thank's for you question @artmarydotir

**Comment by alijahanpak** [comment]
use :  sudo vuepress dev
