### ISSUE TITLE
Vue Package version mismatch

### ISSUE THREAD

**Issue by realtebo** [vuejs/vuepress#2180]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

```
cd c:\progetti
yarn global add vuepress   
mkdir vuepress-starter 
cd vuepress-starter  
echo '# Hello VuePress' > README.md 
vuepress dev                                                                                                                                                                                       C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@2.6.10
- vue-server-renderer@2.6.11

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\vue-server-renderer\index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\lib\node\build\index.js:11:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

#### What is expected?
```

Simply, it must start dev server, I think. It's my first time here

#### What is actually happening?

As you can can see above, I  have a blocking error.

#### Other relevant information

I am on Windows 10 Pro. Never tried to install vuepress first of today, so I expect all is fresh and updated.

- Output of `npx vuepress info` in my VuePress project:

```
C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@2.6.10
- vue-server-renderer@2.6.11

This may cause things to work incorrectly. Make sure to use the same version for both.

    at Object.<anonymous> (C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\vue-server-renderer\index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\@vuepress\core\lib\node\build\index.js:11:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by meteorlxy** [comment]
You might have installed vue@2.6.10 globally (via some other package, maybe `vue-cli`).

1. Install vuepress locally, instead of globally.

2. Or, if you still want global installation, try `yarn global add vue@2.6.11`.

**Comment by realtebo** [comment]
![image](https://user-images.githubusercontent.com/1268699/74643348-d9c76100-5174-11ea-97c4-81b17d6ec85d.png)

I did what I wrote in the issue. And I did what your "getting started" told me to do.

So please, instead of easily close the issue, understand that something is wrong by your side

**Comment by meteorlxy** [comment]
> You might have installed vue@2.6.10 globally (via some other package, maybe vue-cli).

Can't you see that?

**Comment by realtebo** [comment]
We haven't vue installed locally


Yarn
```
yarn global remove vue                                                                                                                                                    yarn global v1.21.1
[1/2] Removing module vue...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
    
NPM                                                   
```

 npm remove vue -g
up to date in 0.03s


```

Anyway
```

vuepress dev                                                                                                                                                              
C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\vue-server-renderer\index.js:8
  throw new Error(
  ^

Error:

Vue packages version mismatch:

- vue@2.6.10
- vue-server-renderer@2.6.11
```

**Comment by meteorlxy** [comment]
Have you tried `yarn global add vue@2.6.11` ?

If it does not work, you can try to check the version of vue that installed in the `C:\Users\Utente\AppData\Local\Yarn\Data\global\node_modules\` path.

Or, try something like:
- Clean the cache
- Remove everything and re-install
- ...

---

Anyway, it's not suggested to install vuepress globally if you want to use it in a real project.

**Comment by uniquejava** [comment]
I have the same issue, I should have a clean mac.
I followed the document 

```
yard global add vuepress
 ```

and then i tried `vue --version`


> Error:
> 
> Vue packages version mismatch:
> 
> - vue@2.6.10
> - vue-server-renderer@2.6.11

I fixed this by running ` yarn global add vue@2.6.11`. so if it's not a bug I think you'd mention please run the following command together in the getting started guide.

```
yard global add vuepress
yarn global add vue@2.6.11
```

**Comment by realtebo** [comment]
I absolutely disagree.

It's not a solution to add vue globally, absolutely. In a server, or a complex dev environmente, we could have a lot of conflicts

**Comment by polyamide** [comment]
I have the same issue. But instead of installing it globally, I would recommend to upgrade your local Vue to version 2.6.11.

Because vue-server-renderer's package.json didn't specify which Vue version it depends upon, So Npm and Yarn will install latest vue-server-renderer version specified by `@vuepress/core` which is 2.6.11. 

Despite the fact that Vue 2.6.10 is already installed, so the latest supported version of vue-server-renderer should be 2.6.10, not 2.6.11.

**Comment by bruceeewong** [comment]
Agree with polyamide. Just upgrade the local Vue to version 2.6.11,  and trouble disappeared.

**Comment by pedropcruz** [comment]
anyone get a solution for this? thanks

**Comment by ashwinkshenoy** [comment]
I had a similar issue.
I fixed it by doing `npm install vue-server-renderer --save-dev`


Keep in mind, if you are using specific version of vue like
```
"dependencies": {
    "vue": "2.6.12",
   ...
},
```
Then your `vue-server-renderer` should also be the same version in `package.json` without `~` or `^`
```
"devDependencies": {
    "vue-server-renderer": "2.6.12", 
   ...
},
```
