### ISSUE TITLE
vuepress build，cannot find  '/dist/manifest/client.json' 

### ISSUE THREAD

**Issue by yulei521** [vuejs/vuepress#2194]
![image](https://user-images.githubusercontent.com/13927415/75016404-e2e26600-54c5-11ea-82fe-0bdd205edc96.png)

**Comment by ludanxer** [comment]
Hi @yulei521 , could you please follow issue template and provide more context?

And please use English so everyone could understand and help you.

**Comment by kngako** [comment]
- [x] I confirm that this is an issue rather than a question.






## Bug report

Vuepress fails to build on Ubuntu 18.04.4 even though dev works successfully.

#### Steps to reproduce

```bash
git clone https://github.com/vuejs/vuepress.git
cd vuepress
yarn install
npm run build
```





#### What is expected?

This should build successfully.

#### What is actually happening?

The build fails and produces this error:
```
> @ build /home/sigidli/Documents/dev/vuepress
> yarn tsc && yarn build:docs

yarn run v1.21.1
$ yarn workspace @vuepress/shared-utils tsc
$ tsc
Done in 6.52s.
yarn run v1.21.1
$ yarn workspace docs build
$ vuepress build docs --temp .temp
wait Extracting site metadata...
tip Apply theme @vuepress/theme-vue (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
tip Apply plugin flowchart (i.e. "vuepress-plugin-flowchart") ...

✔ Client
  Compiled successfully in 35.24s

✔ Server
  Compiled successfully in 35.17s

Error: Cannot find module '/home/sigidli/Documents/dev/vuepress/vuepress/manifest/client.json'
Require stack:
- /home/sigidli/Documents/dev/vuepress/packages/@vuepress/core/lib/node/build/index.js
- /home/sigidli/Documents/dev/vuepress/packages/@vuepress/core/lib/node/App.js
- /home/sigidli/Documents/dev/vuepress/packages/@vuepress/core/lib/index.js
- /home/sigidli/Documents/dev/vuepress/packages/vuepress/lib/registerCoreCommands.js
- /home/sigidli/Documents/dev/vuepress/packages/vuepress/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Build.render (/home/sigidli/Documents/dev/vuepress/packages/@vuepress/core/lib/node/build/index.js:56:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async App.build (/home/sigidli/Documents/dev/vuepress/packages/@vuepress/core/lib/node/App.js:498:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/share/yarn/lib/cli.js build
Directory: /home/sigidli/Documents/dev/vuepress/packages/docs
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `yarn tsc && yarn build:docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```

Environment Info:

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.7 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 73.0
  npmPackages:
    @vuepress/core:  1.3.1 
    @vuepress/theme-default:  1.3.1 
    vuepress:  1.3.1 
  npmGlobalPackages:
    vuepress: Not Found

```

**Comment by kngako** [comment]
Looks like this issue doesn't occur when `NODE_ENV` is set to `production`. So running
```bash
NODE_ENV=production npm run build
```

Lets everything work as it should.

The check for production was [introduced 2 years ago](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/node/webpack/createClientConfig.js#L35) and it looks like it's a feature instead of a bug.

**Comment by yulei521** [comment]
@kngako get it，thank you。

**Comment by virtuecoder** [comment]
I think this should be included in the "Gettings Started" section of the docs. Otherwise most of the  people are going to bump into that trap.
