### ISSUE TITLE
Type Error: this._router.use is not a function

### ISSUE THREAD

**Issue by brookmg** [vuejs/vuepress#2239]
- [x] I confirm that this is an issue rather than a question.

## Bug report
+ Starting the dev server fails with a type error

#### Steps to reproduce
`npm run doc:dev`

#### What is expected?
+ To start the development server

#### What is actually happening?
```
TypeError: this._router.use is not a function
    at Function.lazyrouter (/.../GitHub/TOE_Backend/node_modules/express/lib/application.js:144:18)
    at Function.all (/.../GitHub/TOE_Backend/node_modules/express/lib/application.js:498:8)
    at Server.setupCheckHostRoute (/.../TOE_Backend/node_modules/webpack-dev-server/lib/Server.js:192:14)
    at new Server (/.../GitHub/TOE_Backend/node_modules/webpack-dev-server/lib/Server.js:117:10)
    at DevProcess.createServer (/.../GitHub/TOE_Backend/node_modules/@vuepress/core/lib/node/dev/index.js:238:19)
    at error (/.../GitHub/TOE_Backend/node_modules/@vuepress/core/lib/node/App.js:476:14)
    at new Promise (<anonymous>)
    at App.dev (/.../GitHub/TOE_Backend/node_modules/@vuepress/core/lib/node/App.js:469:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
#### Other relevant information
+ Using Windows WSL 
- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.21.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.4.0
    @vuepress/theme-default:  1.4.0
    vuepress: ^1.4.0 => 1.4.0
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ludanxer** [comment]
Hi, can you share your repo? Or provide a minimal reproduction? Thanks!

**Comment by brookmg** [comment]
My repo is currently private and I couldn't reproduce it by creating a new project. So am going to close this as it's not a bug in vuepress. Sorry guys.
