### ISSUE TITLE
TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by ijandc** [vuejs/vuepress#2288]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

首先安装markdownit插件：
`yarn add markdown-it-mermaid -D`
其次在config.js中开启这个插件：
```
markdown: {
            extendMarkdown: md => {
                // 使用更多的 markdown-it 插件!
                md.use(require('markdown-it-mermaid'), {enabled: true})
            }
        },
```
然后
`vuepress dev docs`

#### What is expected?

代码块可以识别`mermaid`流程，并将其显示为流程而不是代码

#### What is actually happening?

加载markdown-it-mermaid插件的时候报错了`TypeError: plugin.apply is not a function`:
```
TypeError: plugin.apply is not a function
    at MarkdownIt.use (/Users/jcmac/TC/jpdocs/node_modules/markdown-it/lib/index.js:496:10)
    at extendMarkdown (/Users/jcmac/TC/jpdocs/docs/.vuepress/config.js:64:20)
    at afterInstantiate (/Users/jcmac/TC/jpdocs/node_modules/@vuepress/core/lib/node/createMarkdown.js:23:23)
    at module.exports (/Users/jcmac/TC/jpdocs/node_modules/@vuepress/markdown/index.js:124:23)
    at module.exports (/Users/jcmac/TC/jpdocs/node_modules/@vuepress/core/lib/node/createMarkdown.js:27:10)
    at App.process (/Users/jcmac/TC/jpdocs/node_modules/@vuepress/core/lib/node/App.js:113:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async dev (/Users/jcmac/TC/jpdocs/node_modules/@vuepress/core/lib/index.js:17:3)

```
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 13.12.0 - /var/folders/m6/b1p0wr4n7lgg59cgz3klvrhw0000gn/T/yarn--1586307712860-0.19460731876860216/node
    Yarn: 1.22.4 - /var/folders/m6/b1p0wr4n7lgg59cgz3klvrhw0000gn/T/yarn--1586307712860-0.19460731876860216/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.4.0 
    @vuepress/theme-default:  1.4.0 
    vuepress: ^1.3.1 => 1.4.0 
  npmGlobalPackages:
    vuepress: Not Found

```

**Comment by meteorlxy** [comment]
Seems that it's about `markdown-it` and `markdown-it-mermaid`, but not related to VuePress
