### ISSUE TITLE
Failed to resolve filter: moment

### ISSUE THREAD

**Issue by saltbo** [vuejs/vuepress#2291]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
When rendering the following Markdown content:

> When using, if it is in the dom structure, the usage is`{{ data.time | moment }}`。

#### What is expected?
Normal output.

#### What is actually happening?
Failed readering. Treat the text content as vue code!

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
[Vue warn]: Failed to resolve filter: moment

(found in <V4c7cc606>)
[Vue warn]: Error in render: "TypeError: Cannot read property 'time' of undefined"

found in

---> <V4c7cc606>
       <Content>
         <Page>
           <Layout>
             <GlobalLayout>
               <Root>
error Error rendering /_posts/vue-summary.html: false
undefined
TypeError: Cannot read property 'time' of undefined
    at Proxy.render (_posts/vue-summary.md?80cb:1:18888)
    at VueComponent.Vue._render (/usr/local/lib/node_modules/vuepress/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8426:3)
    at renderComponent (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8383:5)
    at renderNode (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8294:5)
    at resolve (/usr/local/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.dev.js:8421:5)
    at waitForServerPrefetch (/usr/local/lib/node_modules/vuepress/node_mod
```

**Comment by ludanxer** [comment]
You'll need to wrap it with the `v-pre` custom container:

```markdown
::: v-pre
{{ data.time | moment }}
:::
```

check out the [documentation](https://vuepress.vuejs.org/guide/using-vue.html#escaping) for more detail

**Comment by saltbo** [comment]
How can i disable the feature Using Vue in Markdown

**Comment by newsbielt703** [comment]
> How can i disable the feature Using Vue in Markdown, becouse i don't want change my article.

No such feature for now.
