### ISSUE TITLE
Updating config.js or YAML Frontmatter don't trigger Hot Reload

### ISSUE THREAD

**Issue by tecnoloco** [vuejs/vuepress#2437]
- [ x] I confirm that this is an issue rather than a question.

## Bug report

Updating config.js or YAML Frontmatter don't trigger Hot Reload.

#### Steps to reproduce
Change values inside config.js or in YAML Frontmatter in .md files.

#### What is expected?
Hot reload with the changes applied.
#### What is actually happening?
Hot reload is not happening, changes are not being rendered.
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by thominal** [comment]
+1 Same issue on my side.

**Comment by adamdehaven** [comment]
Same here. For reference, here's the error I receive when updating the `config.js` file:

``` sh
error @vuepress/plugin-blog apply clientDynamicModules failed.
(node:18288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reduce' of undefined
    at clientDynamicModules (D:\adam\Development\vuepress\node_modules\@vuepress\plugin-blog\lib\node\index.js:91:81)
    at ClientDynamicModulesOption.asyncApply (D:\adam\Development\vuepress\node_modules\@vuepress\core\lib\node\plugin-api\abstract\AsyncOption.js:33:21)
    at async ClientDynamicModulesOption.apply (D:\adam\Development\vuepress\node_modules\@vuepress\core\lib\node\plugin-api\override\ClientDynamicModulesOption.js:15:5)
    at async PluginAPI.applyAsyncOption (D:\adam\Development\vuepress\node_modules\@vuepress\core\lib\node\plugin-api\index.js:277:5)
    at async Promise.all (index 0)
    at async App.process (D:\adam\Development\vuepress\node_modules\@vuepress\core\lib\node\App.js:124:5)
(node:18288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zhaokgithub** [comment]
Same here

**Comment by baayukurnia** [comment]
upgrade to `node 14.x` fixed this issue for me.

**Comment by coffeephile** [comment]
I tried updating to Node 14.x on Windows 10, but still no luck.

Light hot reload (markdown hot reload) works fine, but deep hot reload (config.js changes, frontmatter changes) gets stuck on the terminal and I don't see the updates on the site.

No issues on Mac though.

**Comment by surjithctly** [comment]
+1

Following up on this. Have same issue.

**Comment by SimZhou** [comment]
Same here.

**Comment by SimZhou** [comment]
update5: Partially **Solved**!

By running the local server with option `--temp .temp`! 

Specifically, in `package.json`, substitute:
```
"dev": "vuepress dev docs",   
```
by 
```
"dev": "vuepress dev docs --temp .temp",   
```

This creates you a temporary folder ".temp" for your dev server. 
If you don't want this to be pushed to your remote repo, just add this folder name in your `.gitignore` file. 

@bencodezen So it seems there's sth wrong with the temp files, sadly I know little javascript, otherwise I would glad to solve it myself.

**Comment by surjithctly** [comment]
@SimZhou Not working for me. Tried your ``temp fix but after reloading, it goes blank.

**Comment by SimZhou** [comment]
update6: I've tried the method again, on another win10 PC with a brand new environment (hasn't even installed nodejs before).
And the `--temp` fix still works. 

@surjithctly Blank page might come from other unknown issues. I've encountered it once as well and solved by reinstalling vuepress `npm install -D vuepress`. Don't know if it would also work on your side.

**Comment by aceven24** [comment]
Might have posted to wrong issue, but I have issues with frontmatter not hotloading..

Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
  Binaries:
    Node: 12.13.1 - ~\AppData\Local\Temp\yarn--1593533765469-0.49432315341001365\node.CMD
    Yarn: 1.21.1 - ~\AppData\Local\Temp\yarn--1593533765469-0.49432315341001365\yarn.CMD
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core:  1.5.2
    @vuepress/theme-default:  1.5.2
    vuepress: ^1.5.2 => 1.5.2
  npmGlobalPackages:
    vuepress: Not Found

**Comment by aceven24** [comment]
Anyone got ideas on this?

**Comment by surjithctly** [comment]
@aceven24  #1283

**Comment by sdwru** [comment]
> @SimZhou Not working for me. Tried your ``temp fix but after reloading, it goes blank.

Not working for me either.  I've tried all the fixes.  None of them work.  I think there may be more than one issue that are only loosely related.

**Comment by SimZhou** [comment]
Evan You is now working on Vitepress, which is a new version of vuepress, along with vue 3.0...It uses vite to handle hot reloading now, instead of webpack. (In a recent interview Evan also said his initiative to build vite was originally for a better vuepress experience, I don't know if it includes this bug)

Anyway...I think soon this bug would no longer be important...since vite would be way faster than webpack.
