### ISSUE TITLE
有{{...}} 时build出错

### ISSUE THREAD

**Issue by wgf4242** [vuejs/vuepress#2463]
#### Steps to reproduce
含有下面内容时build出错

1.md

    `{{...}}`

vuepress build .

然后就报错了

#### What is actually happening?
```
D:\wgf\My Documents\Github\blog\del_vuepress>vuepress build .
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...



* Client █████████████████████████ building (69%) 506/507 modules 1 active
 ...s-loader » ..\..\..\..\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\.temp\style.styl

× Server
  Compiled with some errors in 7.24s

(node:13136) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13136) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:13136) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:13136) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:13136) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:13136) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency

× Client
  Compiled with some errors in 8.26s

× Server
  Compiled with some errors in 7.24s

(undefined) ./1.md?vue&type=template&id=59c4a766& (D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"../../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"cb41188e-vue-loader-template"}!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js??ref--1-0!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib??ref--1-1!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/markdown-loader??ref--1-2!./1.md?vue&type=template&id=59c4a766&)
Module build failed (from D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:143)
    at Parser.pp$4.raise (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2757:13)
    at Parser.pp.unexpected (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:647:8)
    at Parser.pp$3.parseExprAtom (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2196:10)
    at Parser.<anonymous> (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:6003:24)
    at Parser.parseExprAtom (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
    at Parser.pp$3.parseExprOps (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$2.parseSpread (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1653:24)
    at Parser.pp$3.parseExprList (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2659:20)
    at Parser.pp$3.parseSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
    at Parser.pp$3.parseExprOps (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$3.parseExprList (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
 @ ./1.md?vue&type=template&id=59c4a766& 1:0-779 1:0-779
 @ ./1.md
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/.temp/internal/page-components.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/util.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/app.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) ./1.md?vue&type=template&id=59c4a766& (D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"../../../../AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"520cc585-vue-loader-template"}!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js??ref--1-0!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib??ref--1-1!D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/markdown-loader??ref--1-2!./1.md?vue&type=template&id=59c4a766&)
Module build failed (from D:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:143)
    at Parser.pp$4.raise (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2757:13)
    at Parser.pp.unexpected (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:647:8)
    at Parser.pp$3.parseExprAtom (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2196:10)
    at Parser.<anonymous> (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:6003:24)
    at Parser.parseExprAtom (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
    at Parser.pp$3.parseExprOps (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$2.parseSpread (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1653:24)
    at Parser.pp$3.parseExprList (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2659:20)
    at Parser.pp$3.parseSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
    at Parser.pp$3.parseExprOps (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$3.parseExprList (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (D:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
 @ ./1.md?vue&type=template&id=59c4a766& 1:0-779 1:0-779
 @ ./1.md
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/.temp/internal/page-components.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/util.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/app.js
 @ d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi d:/wgf/AppData/Roaming/npm/node_modules/vuepress/node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\build\index.js:180:16
    at finalCallback (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\neo-async\async.js:2931:13)
    at runCompilers (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\MultiCompiler.js:188:7
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compiler.js:257:39)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compiler.js:271:21)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\Hook.js:154:20)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\Hook.js:154:20)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\tapable\lib\Hook.js:154:20)
    at d:\wgf\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\Compilation.js:1414:32
```

**Comment by baixiaoyu2997** [comment]
使用`{{` 需要添加`v-pre`。参考：https://v1.vuepress.vuejs.org/zh/guide/using-vue.html#escaping
