### ISSUE TITLE
when add the head configuration like favicon in the .config.js, build error。

### ISSUE THREAD

**Issue by Jinwan5290** [vuejs/vuepress#2620]
code as follows
`module.exports = {
  base: '/docs/',
  title: 'mrapi',
  description: 'mrapi docs',
  head: ['link', { rel: 'icon', href: '/assets/favico.ico' }],
...
}
`
and dev is ok
but when i build 
The error occurred：
`
TypeError: undefined is not a function
    at /Users/jinwan/Desktop/work-project/mrapi-docs/node_modules/@vuepress/core/lib/node/build/index.js:101:15
    at Array.filter (<anonymous>)
    at Build.render (/Users/jinwan/Desktop/work-project/mrapi-docs/node_modules/@vuepress/core/lib/node/build/index.js:101:8)
    at async App.build (/Users/jinwan/Desktop/work-project/mrapi-docs/node_modules/@vuepress/core/lib/node/App.js:499:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`
then I enter the source code to view
and see 
![image](https://user-images.githubusercontent.com/49583674/93750810-ae3ab680-fc2e-11ea-8f2b-50f1b67d7506.png)
in the debug 
we can see there is no function called userHeadTags on the this instance
![image](https://user-images.githubusercontent.com/49583674/93750912-d62a1a00-fc2e-11ea-87e5-7b4257332c68.png)
so how can solve this

**Comment by Jinwan5290** [comment]
sorry I wrote it wrongly
