### ISSUE TITLE
Failed to compile using vuepress build

### ISSUE THREAD

**Issue by anthonypiccolo** [vuejs/vuepress#2647]
Hi all,

I'm using this guide to build and deploy my VuePress site using Firebase; https://www.damien-springuel.ca/blog/posts/vuepress-firebase.html#vuepress

However, when running `vuepress build` I get errors. Anyone know what could be causing this?

```
Error: Failed to compile with errors.
    at /usr/local/lib/node_modules/vuepress/node_modules/@vuepress/core/lib/node/build/index.js:180:16
    at finalCallback (/usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/usr/local/lib/node_modules/vuepress/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:257:39)
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:271:21)
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/vuepress/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/vuepress/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/local/lib/node_modules/vuepress/node_modules/webpack/lib/Compiler.js:678:31
```

Any help would be greatly appreciated!

Thanks

**Comment by heycn** [comment]
Me too, please help...

**Comment by SanGongHappy** [comment]
I encountered the same issue, and it was resolved when I downgraded my npm version to 16.
