### ISSUE TITLE
Why can't I build my vuepress site?

### ISSUE THREAD

**Issue by anthonypiccolo** [vuejs/vuepress#2652]
Does anyone know why my vuepress site won't build with `npm run docs:build`? I get this error...

```
Error: Failed to compile with errors.
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/@vuepress/core/lib/node/build/index.js:180:16
    at finalCallback (/Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/anthony.piccolo/dev/nbamodel/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/anthony.piccolo/dev/nbamodel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/anthony.piccolo/dev/nbamodel/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/anthony.piccolo/dev/nbamodel/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/anthony.piccolo/dev/nbamodel/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/anthony.piccolo/dev/nbamodel/node_modules/webpack/lib/Compiler.js:678:31
```

It seems if I run `npm run docs:build` in the root directory it doesn't work, from same directory if I run `vuepress build` it works. But then if I run either command in docs it doesn't work. Basically I need to be able to build within docs... why won't it let me?

My `package.json` looks like this;

```
{
  "name": "nbamodel",
  "version": "1.0.0",
  "description": "NBA betting model",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "author": "Anthony Piccolo",
  "license": "ISC",
  "devDependencies": {
    "vuepress": "^1.6.0"
  }
}
```

**Comment by d-pollard** [comment]
Hi @anthonypiccolo 

This seems like a question and as such, would be better suited for stackoverflow.com
