### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zq99299** [vuejs/vuepress#2755]
- [ x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

When I was building a very large project, an exception occurred：RangeError: Maximum call stack size exceeded

```
git clone https://github.com/zq99299/note-book.git
git checkout vuepress-issue
yarn install
yarn docs:build

# yarn docs:build  The following command is used
node --max_old_space_size=5096 ./node_modules/vuepress/cli.js build docs --debug

# The following command also failed to build
node --max_old_space_size=5096  --stack-size=1000  ./node_modules/vuepress/cli.js build docs --debug
```

tips: I deleted the book content that was added later, but it still cannot be built. It could be built successfully before, but now I don't know why it is like this
注：我把后来增加的书籍内容删掉了，还是不能构建，之前是可以成功构建的，现在不知道为什么会这样

#### What is expected?

Build success

#### What is actually happening?
Build failed

```
...
debug Cache identifier : {"vuepress":"1.7.1","cache-loader":"3.0.1","vue-loader":"3.0.1","isProd":true,"config":"{\"lineNumbers\":true,\"html\":true}"}
debug Dist directory: C:\Users\zq\Desktop\note\note-book\build\.vuepress\dist
debug applySyncOption: define
debug applySyncOption: alias
debug applySyncOption: chainWebpack
debug applySyncOption: define
debug applySyncOption: alias
debug applySyncOption: chainWebpack
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\zq\Desktop\note\note-book\node_modules\@vuepress\core\.temp\internal\siteData.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\zq\Desktop\note\note-book\node_modules\@vuepress\core\.temp\internal\siteData.js as it exceeds the max of 500KB.
wait Rendering static HTML...
[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"

found in
.....

RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at matchRoute (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1683:16)
    at match (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1557:13)
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1617:14)
    at _createRoute (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1656:14)
    at match (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1558:18)
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1617:14)
    at _createRoute (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1656:14)
    at match (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1558:18)
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1617:14)
    at _createRoute (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1656:14)
    at match (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1558:18)
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1617:14)

...

(node:51852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non
-zero exit code.
(node:51852) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1576:7)
    at _createRoute (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1656:14)
    at match (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1558:18)
    at redirect (C:\Users\zq\Desktop\note\note-book\node_modules\vue-router\dist\vue-router.common.js:1617:14)

```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.10.1 - D:\ProgramFiles\node\nodejs\node.EXE
    Yarn: 1.9.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - D:\ProgramFiles\node\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @vuepress/core:  1.7.1
    @vuepress/theme-default:  1.7.1
    vuepress: ^1.7.1 => 1.7.1
  npmGlobalPackages:
    vuepress: Not Found

```

**Comment by zq99299** [comment]
@ulivz Can you help me solve it

**Comment by zq99299** [comment]
#2656 

I'm almost finished deleting my notes, and I'm still reporting errors. I doubt life.
Fortunately, I saw this issue at last
