### ISSUE TITLE
@babel/preset-env: The plugins/built-ins 'es.array.iterator, es.promise, es.object.assign, es.promise.finally' passed to the 'exclude' option are not valid.

### ISSUE THREAD

**Issue by xon52** [vuejs/vuepress#2838]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Every time I try and dev or build my docs, I get the following error:

```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] D:\Dropbox\Projects\test\node_modules\@vuepress\core\lib\client\clientEntry.js: @babel/preset-env: The plugins/built-ins 'es.array.iterator, es.promise, es.object.assign, es.promise.finally' passed to the 'exclude' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "D:\\Dropbox\\Projects\\test\\node_modules\\@vue\\babel-preset-app\\index.js.overrides[0]$0")
    at OptionValidator.invariant (D:\Dropbox\Projects\test\node_modules\@babel\helper-validator-option\lib\validator.js:48:13)
    at expandIncludesAndExcludes (D:\Dropbox\Projects\test\node_modules\@babel\preset-env\lib\normalize-options.js:51:5)
    at normalizeOptions (D:\Dropbox\Projects\test\node_modules\@babel\preset-env\lib\normalize-options.js:130:19)
    at D:\Dropbox\Projects\test\node_modules\@babel\preset-env\lib\index.js:277:37
    at D:\Dropbox\Projects\test\node_modules\@babel\helper-plugin-utils\lib\index.js:22:12
    at async (D:\Dropbox\Projects\test\node_modules\@babel\core\lib\gensync-utils\async.js:33:33)
    at async (D:\Dropbox\Projects\test\node_modules\gensync\index.js:186:15)
    at D:\Dropbox\Projects\test\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at D:\Dropbox\Projects\test\node_modules\@babel\core\lib\config\full.js:213:21
    at Generator.next (<anonymous>)
```

#### Steps to reproduce
Check out my [x5-gmaps repo](https://github.com/xon52/x5-gmaps), and run `npm run docs:dev` (and open up the localhost link), or `npm run docs:build`.
You can also see the failed [Github Pages build](https://github.com/xon52/x5-gmaps/runs/2489265474).

#### What is expected?
No errors and docs displaying/building.

#### What is actually happening?
Errors and no docs displaying/building.

#### Other relevant information
- I have had this once before and I don't even know what changed to fix it.
- If I put `@vue/babel-preset-app` as a babel preset in a regular project I get the same error (for that project)
- I have testing updating VuePress to v1.8.2 without any change in the result.

- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
  Binaries:
    Node: 15.12.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - D:\Program Files\Yarn\bin\yarn.CMD
    npm: 7.6.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.18362.1474.0)
  npmPackages:
    @vuepress/core:  1.8.2
    @vuepress/theme-default:  1.8.2
    vuepress: ^1.5.3 => 1.8.2
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by EwertonDCSilv** [comment]
I have the same problem !

**Comment by shijunti19** [comment]
me too
