### ISSUE TITLE
UnhandledPromiseRejectionWarning when rendering static HTML

### ISSUE THREAD

**Issue by huangjianhua567** [vuejs/vuepress#2863]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
`wait Rendering static HTML...
How to use ""valine"" in vuepress-plugin-comment@v0.7.3: https://github.com/dongyuanxin/vuepress-plugin-comment#readme
(node:17316) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at Module.549 (9.server-bundle.js:232:40)
    at __webpack_require__ (server-bundle.js:27:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was 
not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

#### Other relevant information
`PS E:\测试个人博客2\blog> node --trace-warnings ...
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'E:\测试个人博客2\blog\...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`
- Output of `npx vuepress info` in my VuePress project:
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\Program Files\nodejs\node_global\yarn.CMD
    npm: 6.14.13 - E:\测试个人博客2\blog\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
  npmPackages:
    @vuepress/core:  1.8.2
    @vuepress/theme-default:  1.8.2
    vuepress: 1.8.2 => 1.8.2
  npmGlobalPackages:
    vuepress: Not Found

**Comment by zhaoyuhang1033** [comment]
same

**Comment by zhaoyuhang1033** [comment]
yarn add vue-router  我也不知道为啥然后就行了
