### ISSUE TITLE
optimize-css-assets-webpack-plugin version bug

### ISSUE THREAD

**Issue by RhysXia** [vuejs/vuepress#2875]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

see [this issue](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/167)

optimize-css-assets-webpack-plugin released version 5.0.7 a few hours ago. Compared with 5.0.6, one of the changes is that postcss has changed from transitively dependent 7.x to 8.x, causing build errors.

#### What is expected?

build passed

#### What is actually happening?

build failed

**Comment by cq360767996** [comment]
I have the same problem. Is there any solutions?

**Comment by superZchen0701** [comment]
there are someone resolve the problem?

**Comment by wangdaodao** [comment]
build failed!

**Comment by simllll** [comment]
```
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (/buddy/node_modules/postcss/lib/lazy-result.js:528:33)
    at LazyResult.runAsync (/buddy/node_modules/postcss/lib/lazy-result.js:408:30)
    at LazyResult.async (/buddy/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/buddy/node_modules/postcss/lib/lazy-result.js:206:17)
    at OptimizeCssAssetsWebpackPlugin.processCss (/buddy/node_modules/optimize-css-assets-webpack-plugin/src/index.js:81:8)
    at Object.processor (/buddy/node_modules/optimize-css-assets-webpack-plugin/src/index.js:20:18)
    at /buddy/node_modules/last-call-webpack-plugin/src/index.js:150:10
    at arrayEach (/buddy/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/buddy/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/buddy/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at /buddy/node_modules/last-call-webpack-plugin/src/index.js:178:28
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/buddy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:17)
    at AsyncSeriesHook.lazyCompileHook (/buddy/node_modules/tapable/lib/Hook.js:154:20)
    at /buddy/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/buddy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/buddy/node_modules/tapable/lib/Hook.js:154:20)
```
