### ISSUE TITLE
When vuepress introduces “fabric” third party component build, an error is reported

### ISSUE THREAD

**Issue by yizhilian1314** [vuejs/vuepress#2887]
(undefined) ./node_modules/canvas/build/Release/canvas.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/canvas/lib/bindings.js 3:17-56
 @ ./node_modules/canvas/lib/canvas.js
 @ ./node_modules/canvas/index.js
 @ ./node_modules/jsdom/lib/jsdom/utils.js
 @ ./node_modules/fabric/dist/fabric.js
 @ ./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./packages/fabric-chart/src/FabricGrid.vue?vue&type=script&lang=js&
 @ ./packages/fabric-chart/src/FabricGrid.vue?vue&type=script&lang=js&
 @ ./packages/fabric-chart/src/FabricGrid.vue
 @ ./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./packages/fabric-chart/src/FabricChart.vue?vue&type=script&lang=js&
 @ ./packages/fabric-chart/src/FabricChart.vue?vue&type=script&lang=js&
 @ ./packages/fabric-chart/src/FabricChart.vue
 @ ./packages/fabric-chart/index.js
 @ ./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./docs/.vuepress/components/c-fabric-chart.vue?vue&type=script&lang=js&
 @ ./docs/.vuepress/components/c-fabric-chart.vue?vue&type=script&lang=js&
 @ ./docs/.vuepress/components/c-fabric-chart.vue
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/global-components-1.js
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at D:\zuobiao\cnhis-design-vue\node_modules\@vuepress\core\lib\node\build\index.js:180:16
    at finalCallback (D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (D:\zuobiao\cnhis-design-vue\node_modules\neo-async\async.js:2931:13)
    at runCompilers (D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\MultiCompiler.js:188:7
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:257:39)
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\zuobiao\cnhis-design-vue\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (D:\zuobiao\cnhis-design-vue\node_modules\tapable\lib\Hook.js:154:20)
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:499:39)
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:298:10
    at D:\zuobiao\cnhis-design-vue\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\zuobiao\cnhis-design-vue\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xxLion** [comment]
the same problem，I don't know how to solve this problem in config.

I introduced it into the project using CDN, like this
![image](https://user-images.githubusercontent.com/26025205/195018955-cf389154-f622-42c0-aaee-5263c16b39f6.png)

Then use **windows.fabric** in the component，like this
![image](https://user-images.githubusercontent.com/26025205/195019611-f824b44d-3bff-4dfd-adfa-cf7306b3e400.png)
It's not elegant, but it's just documentation and it solves the problem.
