### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Shinigami92** [vuejs/vuepress#2888]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Repo: https://github.com/prettier/plugin-pug

GH Action: https://github.com/prettier/plugin-pug/runs/2975432286?check_suite_focus=true#step:6:1

#### What is expected?

```
yarn install
yarn docs:build
```

=> Should successfully build vuepress docs

#### What is actually happening?

```node
yarn run v1.22.10
$ vuepress build docs
wait Extracting site metadata...
tip Apply theme vuepress-theme-yuu (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin yuu-theme-plugin ...

● Client █████████████████████████ chunk asset optimization (92%) OptimizeCssAssetsWebpackPlugin 
 

✖ Server
  Compiled with some errors in 5.69s


✖ Client
  Compiled with some errors in 8.02s

✖ Server
  Compiled with some errors in 5.69s

(undefined) ./docs/guide/README.md
Module build failed (from ./node_modules/@vuepress/markdown-loader/index.js):
ReferenceError: document is not defined
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/components/prism-markdown.js:354:24
    at Object.run (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:720:6)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:836:11)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:813:10
    at Array.forEach (<anonymous>)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:812:6)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:820:13)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:813:10
    at Array.forEach (<anonymous>)
    at Function.stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:812:6)
    at Object.highlight (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:630:17)
    at Object.module.exports [as highlight] (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/highlight.js:50:24)
    at default_rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/markdown-it/lib/renderer.js:50:27)
    at md.renderer.rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/highlightLines.js:15:16)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/preWrapper.js:14:21
    at Object.md.renderer.rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/snippet.js:109:12)
 @ ./node_modules/@vuepress/core/.temp/internal/page-components.js 10:11-79
 @ ./node_modules/@vuepress/core/lib/client/util.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/clientEntry.js
(undefined) ./docs/guide/README.md
Module build failed (from ./node_modules/@vuepress/markdown-loader/index.js):
ReferenceError: document is not defined
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/components/prism-markdown.js:354:24
    at Object.run (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:720:6)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:836:11)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:813:10
    at Array.forEach (<anonymous>)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:812:6)
    at stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:820:13)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:813:10
    at Array.forEach (<anonymous>)
    at Function.stringify (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:812:6)
    at Object.highlight (/home/shinigami/OpenSource/plugin-pug/node_modules/prismjs/prism.js:630:17)
    at Object.module.exports [as highlight] (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/highlight.js:50:24)
    at default_rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/markdown-it/lib/renderer.js:50:27)
    at md.renderer.rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/highlightLines.js:15:16)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/preWrapper.js:14:21
    at Object.md.renderer.rules.fence (/home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/markdown/lib/snippet.js:109:12)
 @ ./node_modules/@vuepress/core/.temp/internal/page-components.js 10:11-79
 @ ./node_modules/@vuepress/core/lib/client/util.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js
Error: Failed to compile with errors.
    at /home/shinigami/OpenSource/plugin-pug/node_modules/@vuepress/core/lib/node/build/index.js:180:16
    at finalCallback (/home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/home/shinigami/OpenSource/plugin-pug/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/shinigami/OpenSource/plugin-pug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/home/shinigami/OpenSource/plugin-pug/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/shinigami/OpenSource/plugin-pug/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/shinigami/OpenSource/plugin-pug/node_modules/tapable/lib/Hook.js:154:20)
    at /home/shinigami/OpenSource/plugin-pug/node_modules/webpack/lib/Compiler.js:678:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```node
  System:
    OS: Linux 5.10 Arch Linux
    CPU: (28) x64 Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
  Binaries:
    Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.8.2 
    @vuepress/theme-default:  1.8.2 
    vuepress: ~1.8.2 => 1.8.2 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by wl05** [comment]
https://vuepress.vuejs.org/guide/using-vue.html
