### ISSUE TITLE
文件名是中文, docs:build就报错。英文名就正常。

### ISSUE THREAD

**Issue by wgf4242** [vuejs/vuepress#2901]
比如2020-强网杯.md 报下面的错误。 改成英文名直接通过。
```
wait Rendering static HTML...
RangeError: Maximum call stack size exceeded
    at getConstructorName (internal/util/inspect.js:554:9)
    at formatRaw (internal/util/inspect.js:822:23)
    at formatValue (internal/util/inspect.js:812:10)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2016:40)
    at formatWithOptions (internal/util/inspect.js:1898:10)
    at console.value (internal/console/constructor.js:330:14)
    at console.warn (internal/console/constructor.js:363:61)
    at abort (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2081:17)
    at iterator (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2145:7)
    at step (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:1848:9)
    at runQueue (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:1856:3)
    at AbstractHistory.confirmTransition (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2149:3)
    at AbstractHistory.transitionTo (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2036:8)
    at AbstractHistory.push (/Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2589:10)
    at /Users/wudi/Documents/Projects/text/node_modules/vue-router/dist/vue-router.common.js:2137:20
error Error rendering /ctf/writeup/2020-强网杯.html: false
undefined
ReferenceError: pageMeta is not defined
    at Object.eval [as head] (eval at <anonymous> (/Users/wudi/Documents/Projects/text/node_modules/lodash.template/index.js:1550:12), <anonymous>:16:11)
    at TemplateRenderer.render (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:8973:16)
    at RenderContext.done (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:9225:42)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2601:19)
    at RenderContext.cachedWrite [as write] (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2615:25)
    at RenderContext.cachedWrite [as write] (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2615:25)
    at RenderContext.cachedWrite [as write] (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2615:25)
    at RenderContext.cachedWrite [as write] (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2615:25)
    at cachedWrite (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2464:9)
    at renderElement (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:8563:5)
    at RenderContext.renderNode (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:8325:5)
    at RenderContext.next (/Users/wudi/Documents/Projects/text/node_modules/vue-server-renderer/build.dev.js:2611:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wudi/.npm/_logs/2021-07-23T11_46_40_969Z-debug.log
```

**Comment by tb102122** [comment]
Some explanation in English would help.

**Comment by chybcool** [comment]
文件名请问英文，谢谢！
