### ISSUE TITLE
Error: No language registration for C

### ISSUE THREAD

**Issue by yourgracee** [vuejs/vuepress#2947]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
Error: No language registration for C
    at getGrammer (/home/vuepress/node_modules/shiki/dist/index.js:2075:19)
    at codeToThemedTokens (/home/vuepress/node_modules/shiki/dist/index.js:2083:30)
    at Object.codeToHtml (/home/vuepress/node_modules/shiki/dist/index.js:2088:24)
    at Object.md.options.highlight (/home/vuepress/packages/@vuepress/plugin-shiki/lib/node/shikiPlugin.js:12:60)
    at Object.md.renderer.rules.fence (/home/vuepress/packages/@vuepress/markdown/lib/plugins/codePlugin/codePlugin.js:22:88)
    at Renderer.render (/home/vuepress/node_modules/markdown-it/lib/renderer.js:332:38)
    at MarkdownIt.render (/home/vuepress/node_modules/markdown-it/lib/index.js:544:24)
    at MarkdownIt.md.render (/home/vuepress/packages/@vuepress/markdown/lib/plugins/extractHeadersPlugin.js:27:24)
    at MarkdownIt.md.render (/home/vuepress/packages/@vuepress/markdown/lib/plugins/extractTitlePlugin.js:29:24)
    at renderPageContent (/home/vuepress/packages/@vuepress/core/lib/page/renderPageContent.js:14:42)
#### What is expected?

Idk

#### What is actually happening?

can't build successfully

#### Other relevant information

maybe I should update markdown rendering?

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
It looks like an issue of VuePress 2, please move on https://github.com/vuepress/vuepress-next to continue.

// cc @meteorlxy
