### ISSUE TITLE
按照官网操作的，启动报错。卸载重新来，还是报这个错

### ISSUE THREAD

**Issue by alaxury** [vuejs/vuepress#2984]
请问怎么解决呀
D:\codeDemo\blog-demo\vuepress-starter\node_modules\@vuepress\shared-utils\lib\env.js:3
    isDebug;
SyntaxError: Unexpected token ;
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepress-starter@1.0.0 docs:dev: `vuepress dev docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuepress-starter@1.0.0 docs:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FF-C\AppData\Roaming\npm-cache\_logs\2022-01-07T01_24_19_204Z-debug.log
PS D:\codeDemo\blog-demo\vuepress-starter>

**Comment by alaxury** [comment]
用yarn重新来了一遍，不审报错
error Command failed with exit code 1.

【不知道怎么办了】

**Comment by chou1213** [comment]
> 

应该是node版本比较低，换一个node版本试试

**Comment by anprettyboy** [comment]
> 
厉害了，问题解决了，切换到高版本node就解决了

**Comment by GeorgeHcc** [comment]
我node18 npm 和yarn都不会怎么回事呀
run docs:dev的时候就报错了

> vuepress-blog@1.0.0 docs:dev
> vuepress dev docs

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...

* Client █████████████████████████ building (40%) 1/2 modules 1 active
 node_modules\webpack-dev-server\client\index.js

i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\CodeRepository\Blog\vuepress-blog\docs\.vuepress\public
i ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\CodeRepository\Blog\vuepress-blog\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\CodeRepository\Blog\vuepress-blog\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\CodeRepository\Blog\vuepress-blog\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\CodeRepository\Blog\vuepress-blog\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\CodeRepository\Blog\vuepress-blog\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\CodeRepository\Blog\vuepress-blog\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\CodeRepository\Blog\vuepress-blog\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\CodeRepository\Blog\vuepress-blog\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\CodeRepository\Blog\vuepress-blog\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\CodeRepository\Blog\vuepress-blog\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\CodeRepository\Blog\vuepress-blog\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by GeorgeHcc** [comment]
> > 
> 
> 应该是node版本比较低，换一个node版本试试

我的是18，切换到16就可以了（😥虽然18现在已经是LTS了）
