### ISSUE TITLE
document is not defined error when running vuepress build

### ISSUE THREAD

**Issue by arvindanta** [vuejs/vuepress#3019]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

When I run vuepress build [[foldername]], 

```✔ Client
  Compiled successfully in 18.86s

✔ Server
  Compiled successfully in 14.84s

wait Rendering static HTML...
ReferenceError: document is not defined
    at server-bundle.js:6898:5
    at iterator (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2359:7)
    at step (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2006:9)
    at /Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2007:11
    at /Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2381:11
    at server-bundle.js:25607:7
    at iterator (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2359:7)
    at step (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2006:9)
    at runQueue (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2014:3)
    at AbstractHistory.confirmTransition (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2389:3)
    at AbstractHistory.transitionTo (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2262:8)
    at AbstractHistory.push (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:2826:10)
    at /Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:3028:22
    at new Promise (<anonymous>)
    at VueRouter.push (/Users/aashwathanarayanan/Desktop/learning/crayons/node_modules/vue-router/dist/vue-router.common.js:3027:12)
    at server-bundle.js:25947:14
```

It works fine with `dev` server vuepress dev [[foldername]]

Am using vuepress version `1.8.2`.

Kindly help with this issue

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by nagi1** [comment]
confirmed, same problem here too!

**Comment by wangsitingting** [comment]
same problem here too!

**Comment by Mister-Hope** [comment]
Try reading Vue ssr guide.

**Comment by zhoufanglu** [comment]
same problem
