### ISSUE TITLE
MD files with name ending in `index` fails to build

### ISSUE THREAD

**Issue by x8x** [vuejs/vuepress#306]
Markdown file which name ends with `index` fails to build:
- `Gitter-Room-Index.md` -> build fail
- `Gitter-Room-Index_.md` -> build ok

```
Rendering page: /data/file.html[vuepress] No matching page found for sidebar item "/data/Gitter-Room-Index.md"
[vuepress] No matching page found for sidebar item "/data/Gitter-Room-Index.md"
[vuepress] No matching page found for sidebar item "/data/Gitter-Room-Index.md"
Error rendering /data/file.html:
TypeError: Cannot read property 'match' of undefined
    at getHash (vuepress/lib/default-theme/util.js:13:0)
    at isActive (vuepress/lib/default-theme/util.js:43:0)
    at render (vuepress/lib/default-theme/SidebarLink.vue?61b3:10:0)
    at renderWithStyleInjection (vuepress/node_modules/.registry.npmjs.org/vue-loader/15.0.4/node_modules/vue-loader/lib/runtime/componentNormalizer.js:78:0)
    at createFunctionalComponent (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4058:30)
    at createComponent (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4248:12)
    at _createElement (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4418:15)
    at createElement (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4355:10)
    at vm._c (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4487:42)
    at server-bundle.js:14480:650
    at VueComponent.renderList [as _l] (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:3703:16)
    at VueComponent.SidebarGroupvue_type_template_id_325528d9_render (vuepress/lib/default-theme/SidebarGroup.vue?b7ce:1:547)
    at VueComponent.Vue._render (/vuepress/node_modules/.registry.npmjs.org/vue/2.5.16/node_modules/vue/dist/vue.runtime.common.js:4542:22)
    at renderComponentInner (/vuepress/node_modules/.registry.npmjs.org/vue-server-renderer/2.5.16/node_modules/vue-server-renderer/build.js:7521:25)
    at renderComponent (/vuepress/node_modules/.registry.npmjs.org/vue-server-renderer/2.5.16/node_modules/vue-server-renderer/build.js:7491:5)
    at RenderContext.renderNode (/vuepress/node_modules/.registry.npmjs.org/vue-server-renderer/2.5.16/node_modules/vue-server-renderer/build.js:7407:5)
```

**Comment by meteorlxy** [comment]
That may be something related to this issue:

https://github.com/vuejs/vuepress/blob/5023d195dcd7ee6d3710a43558940bcdc31d5a2f/lib/prepare.js#L239

**Comment by x8x** [comment]
@meteorlxy Yea, I was about to post the same ;-)

**Comment by meteorlxy** [comment]
@x8x Would you please help to check if #308 fix this issue?

**Comment by x8x** [comment]
@meteorlxy Works fine here, Thank you! 👍
