### ISSUE TITLE
Error vuepress build.

### ISSUE THREAD

**Issue by miguelTortosaFlit2go** [vuejs/vuepress#3061]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

When doing vuepress build I am getting the following error, 10 days ago I could compile the same project. ERROR --> 

 Reason: TypeError: Cannot read property 'prototype' of undefined
    error Error rendering /: false
    undefined

Error: render function or template not defined in component: anonymous
    at normalizeRender (node_modules/vue-server-renderer/build.dev.js:8292:13)
    at renderComponentInner (node_modules/vue-server-renderer/build.dev.js:8442:3)
    at renderComponent node_modules/vue-server-renderer/build.dev.js:8413:5)
    at resolve (node_modules/vue-server-renderer/build.dev.js:8481:9)

- Output of `npx vuepress info` in my VuePress project:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/108357711/176392671-47a62bbe-d823-44b9-a3d5-d84088281c27.png">

**Comment by lxlneo** [comment]
I have the same problem

**Comment by lengyibai** [comment]
I have the same problem

**Comment by leventefrks** [comment]
I have the same problem too.

**Comment by Liubasara** [comment]
same problem, any progress?
