### ISSUE TITLE
About "error:0308010C:digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by CoolPlayLin** [vuejs/vuepress#3095]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

When I use a node higher than 17, VuePress reports the error `error:0308010C:digital envelope routines::unsupported`

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by chenyigang** [comment]
debian环境，我找到的办法是执行命令
`export NODE_OPTIONS=--openssl-legacy-provider`
解决

**Comment by robertraaijmakers** [comment]
I can confirm that this is quite an issue since with all node versions higher then 16 you will get this error.
Work around is to add 
`set NODE_OPTIONS=--openssl-legacy-provider && vuepress dev`

But this is basically saying yes to a security risk.


node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (...\node_modules\webpack\lib\util\createHash.js:135:53)      
    at NormalModule._initBuildHash (...\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (...\node_modules\webpack\lib\NormalModule.js:471:10)       
    at ..\node_modules\webpack\lib\NormalModule.js:503:5
    at ..\node_modules\webpack\lib\NormalModule.js:358:12
    at ..\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (..\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (..\node_modules\loader-runner\lib\LoaderRunner.js:205:4) 
    at Storage.finished (..\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at ..\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at ..\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by CoolPlayLin** [comment]
Thanks

**Comment by ulivz** [comment]
ref: https://github.com/webpack/webpack/issues/14532
