### ISSUE TITLE
vuepress dev Error

### ISSUE THREAD

**Issue by notjiangjiu** [vuejs/vuepress#3116]
我之前安装过 vue/cli@5.0.8 ，会不会是二者有冲突
I installed vue/cli@5.0.8 before, I wonder if there's a conflict between them

**error**
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
Error: Cannot find module 'vue-template-compiler'
Require stack:
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\compiler.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\plugin-webpack4.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\plugin.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\index.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\webpack\createBaseConfig.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\webpack\createClientConfig.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\dev\index.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\App.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\index.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\lib\registerCoreCommands.js
- C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at loadFromContext (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\compiler.js:30:26)
    at loadTemplateCompiler (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\compiler.js:37:12)
    at exports.resolveCompiler (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\compiler.js:25:23)
    at VueLoaderPlugin.apply (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-loader\lib\plugin-webpack4.js:91:22)
    at webpack (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\webpack\lib\webpack.js:51:13)
    at DevProcess.createServer (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\dev\index.js:241:22)
    at error (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\App.js:477:14)
    at new Promise (<anonymous>)
    at App.dev (C:\Users\manager\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\App.js:470:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by notjiangjiu** [comment]
我尝试用工具安装它，但依然有次问题
I tried to install vue-template-compiler with npm, but there was still a problem
