### ISSUE TITLE
[BUG] VuePress Not Compactable with Node.js v18  

### ISSUE THREAD

**Issue by AkarinLiu** [vuejs/vuepress#3140]
- [x] I confirm that this is an issue rather than a question.

## Bug report
$ yarn dev
yarn run v1.22.19
$ vuepress dev docs
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...   

* Client █████████████████████████ building (40%) 1/3 modules 2 active
 node_modules\webpack\hot\dev-server.js

i ｢wds｣: Project is running at http://0.0.0.0:8080/i ｢wds｣: webpack output is served from /i ｢wds｣: Content not from webpack is served from C:\Users\Scott\Desktop\genshin-ics\docs\.vuepress\public
i ｢wds｣: 404s will fallback to /index.html
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Scott\Desktop\genshin-ics\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Scott\Desktop\genshin-ics\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Scott\Desktop\genshin-ics\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\Scott\Desktop\genshin-ics\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
$ npx vuepress info

Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
  npmPackages:
    @vuepress/core:  1.9.9
    @vuepress/theme-default:  1.9.9
    vuepress: ^1.9.9 => 1.9.9
  npmGlobalPackages:
    vuepress: Not Found

**Comment by bitbegin** [comment]
have same issue

**Comment by AkarinLiu** [comment]
I update to the [vuejs/vuepress-next](https://github.com/vuepress/vuepress-next), everybody update now.

**Comment by AkarinLiu** [comment]
I update to the [vuejs/vuepress-next](https://github.com/vuepress/vuepress-next), everbody update now
