### ISSUE TITLE
最后的部署出错yarn dev 出错

### ISSUE THREAD

**Issue by rjku6** [vuejs/vuepress#3158]
D:\vuepress>yarn -v
1.22.19

D:\vuepress>yarn dev
yarn run v1.22.19
$ vuepress dev docs
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...

* Client █████████████████████████ building (40%) 1/2 modules 1 active
 node_modules\webpack\hot\dev-server.js

i ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\vuepress\docs\.vuepress\public
i ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\vuepress\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\vuepress\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\vuepress\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\vuepress\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\vuepress\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\vuepress\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\vuepress\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\vuepress\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\vuepress\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\vuepress\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\vuepress\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Scorpio-xu** [comment]
我也是这样 好像是node版本太高了 我把node切换到14 可以了

**Comment by rjku6** [comment]
好的，目前换了一个文档docusaurus这个没有这种版本的问题

**Comment by andyklimczak** [comment]
As of this moment, using node 14. 18 and 20 were the other versions I tried that did not work
