### ISSUE TITLE
TypeError: promisify is not a function

### ISSUE THREAD

**Issue by gps67** [vuejs/vuepress#39]
sudo npm install -g vuepress
/usr/bin/vuepress -> /usr/lib/node_modules/vuepress/bin/vuepress.js
/usr/lib
└── vuepress@0.3.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/vuepress/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

# vuepress dev
TypeError: promisify is not a function
    at Object.<anonymous> (/usr/lib/node_modules/vuepress/lib/prepare.js:6:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at dev (/usr/lib/node_modules/vuepress/lib/dev.js:14:19)
    at args (/usr/lib/node_modules/vuepress/bin/vuepress.js:83:12)

**Comment by ulivz** [comment]
Please update your node version to `>=8`.

```js
  // package.json
  "engines": {
    "node": ">=8"
  },
```
