### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by gu18168** [vuejs/vuepress#74]
I just installed vuepress and tried to run `vuepress dev`

/usr/local/lib/node_modules/vuepress/bin/vuepress.js:44
  .action(async (dir = '.') => {
                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by sebbaum** [comment]
I am having the same problem @gu18168 Which version of nodejs are you running?
Mine is v6.14.1
I am wondering if I have to use a newer version.

There are no requirements defined in the documentation

**Comment by egoist** [comment]
hmm you should see an error message when running in node <= 8 

https://github.com/vuejs/vuepress/blob/3c9db8b5a2dd2f6d276cff71a10e4a572c5fb4d1/bin/vuepress.js#L5-L14

**Comment by gu18168** [comment]
@sebbaum Mine is v6.11.5, maybe we should upgrade our Node version

**Comment by sebbaum** [comment]
Hm, no version specific error is shown in my environment, @egoist .

I'll try to upgrade nodejs and see if vuepress is running.

**Comment by sebbaum** [comment]
@gu18168 nodejs >= 8 did the trick. Vuepress is working.
