### ISSUE TITLE
http://npm.spatie.be/@babel%2fcore: no such package available

### ISSUE THREAD

**Issue by lotestudio** [vuejs/vuepress#741]
When trying to install with yarn:
yarn global add vuepress
#### What is actually happening?
Trace: 
  Error: http://npm.spatie.be/@babel%2fcore: no such package available
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:58200:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:114242:22)
      at Request.emit (events.js:182:13)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:115225:10)
      at Request.emit (events.js:182:13)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:115145:12)
      at Object.onceWrapper (events.js:273:13)
      at IncomingMessage.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

#### Other relevant information

- Your OS: macOS High Siera
- Node.js version: 10.8.0
- Which package manager did you use for the install?
yarn

**Comment by ulivz** [comment]
According to the error, it should be an issue of your network.
