### ISSUE TITLE
Error: Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by ChinuxParibus** [vuejs/vuepress#76]
When I try to build the site I coded using the command `vuepress build`, I get this error on console after a while:
```
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ($HOME/.config/yarn/global/node_modules/workbox-build/build/lib/copy-workbox-libraries.js:3:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ($HOME/.config/yarn/global/node_modules/workbox-build/build/index.js:19:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at build ($HOME/.config/yarn/global/node_modules/vuepress/lib/build.js:86:17)
    at <anonymous>
```
I installed `babel-runtime` using this [guide](https://github.com/babel/gulp-babel/issues/50) and installing too the last version of that module.

My `package.json` just look like this
```
{
  //some other fields
  "dependencies": {
    "babel-runtime": "5.3.0",
    "vuepress": "^0.4.0"
  }
}
```

**Comment by yyx990803** [comment]
VuePress doesn't use Babel... I don't know what you are trying to do.

**Comment by ChinuxParibus** [comment]
Well, I just added `babel-runtime` because I thought that it was needed. The only dependency that I had on my project is Vuepress, but when I execute `vuepress build` it gives me that error.

**Comment by yyx990803** [comment]
Your error log seems to be showing trace from a global install instead of a local install. Either way we will need an actual repro to see what's going on.

**Comment by yyx990803** [comment]
Closing due to lack of info/repro. Please follow up for a reopen if you can provide more information.
