### ISSUE TITLE
file name case bug

### ISSUE THREAD

**Issue by willin** [vuejs/vuepress#848]
#### Version

latest stable

#### Steps to reproduce

source here: 
https://github.com/assholev0/v0.chat

#### What is expected?

tested success on my local mac, but travis ci error:

```
$ vuepress build src -d ./dist
 WAIT  Extracting site metadata...
Error: [vuepress] Failed to load custom theme "asshole". File vuepress-theme-asshole/Layout.vue does not exist.
    at resolveOptions (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/lib/prepare/resolveOptions.js:69:15)
    at prepare (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/lib/prepare/index.js:11:25)
    at build (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/lib/build.js:19:25)
    at args (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/bin/vuepress.js:105:12)
    at Command.program.command.description.option.option.action (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/bin/vuepress.js:42:23)
    at Command.listener (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/node_modules/commander/index.js:654:12)
    at Command.parse (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/travis/build/assholev0/v0.chat/node_modules/vuepress/bin/vuepress.js:97:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

details here: 
https://travis-ci.org/assholev0/v0.chat

#### What is actually happening?

'coz my layout file name is 'layout.vue'

we can't tolerate uppercase in filenames which can lead many strange compatibility problems.

besides, underline can be more smooth. like `enhance_app.js`

**Comment by ulivz** [comment]
Vuepress under 1.x. only supports `Layout.vue`.
