### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by l1l31** [vuejs/vuepress#91]
when run `vuepress build`, it's report:
```
TypeError: Cannot read property 'name' of undefined
    at workaroundEmptyStyleChunk (/usr/local/lib/node_modules/vuepress/lib/build.js:171:60)
    at build (/usr/local/lib/node_modules/vuepress/lib/build.js:51:9)
    at <anonymous>
```

**Comment by yyx990803** [comment]
Looks like webpack 4.5 introduced some different behavior. Looking into it...

**Comment by alexcheninfo** [comment]
Sorry, has this issue been fixed?

**Comment by maczyt** [comment]
> Sorry, has this issue been fixed?

update vuepress
