### ISSUE TITLE
TypeError: Cannot read property '_statStorage' of undefined

### ISSUE THREAD

**Issue by youxfans** [vuejs/vuepress#971]
#### Version
`"vuepress": "^1.0.0-alpha.18"`
#### Steps to reproduce

`npm run docs:build`

#### What is expected?
Start correctly
#### What is actually happening?

```
(undefined) ./node_modules/_@vuepress_core@1.0.0-alpha.18@@vuepress/core/lib/app/clientEntry.js
Module build failed (from ./node_modules/_cache-loader@1.2.4@cache-loader/dist/cjs.js):
TypeError: Cannot read property '_statStorage' of undefined
    at stat (/Users/uc/ucwork/ucdevelopers/node_modules/_enhanced-resolve@4.1.0@enhanced-resolve/lib/CachedInputFileSystem.js:231:8)
    at toDepDetails (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:66:5)
    at arrayIterator (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:3780:9)
    at timesSync (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:2292:7)
    at Object.mapLimit (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:3775:5)
    at Array.<anonymous> (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:89:18)
    at arrayEachFunc (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:2512:19)
    at Object.parallel (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:6867:9)
    at Object.loader (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:88:9)
 @ multi ./node_modules/_@vuepress_core@1.0.0-alpha.18@@vuepress/core/lib/app/clientEntry.js app[0]
(undefined) ./node_modules/_@vuepress_core@1.0.0-alpha.18@@vuepress/core/lib/app/serverEntry.js
Module build failed (from ./node_modules/_cache-loader@1.2.4@cache-loader/dist/cjs.js):
TypeError: Cannot read property '_statStorage' of undefined
    at stat (/Users/uc/ucwork/ucdevelopers/node_modules/_enhanced-resolve@4.1.0@enhanced-resolve/lib/CachedInputFileSystem.js:231:8)
    at toDepDetails (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:66:5)
    at arrayIterator (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:3780:9)
    at timesSync (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:2292:7)
    at Object.mapLimit (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:3775:5)
    at Array.<anonymous> (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:89:18)
    at arrayEachFunc (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:2512:19)
    at Object.parallel (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:6867:9)
    at Object.loader (/Users/uc/ucwork/ucdevelopers/node_modules/_cache-loader@1.2.4@cache-loader/dist/index.js:88:9)
 @ multi ./node_modules/_@vuepress_core@1.0.0-alpha.18@@vuepress/core/lib/app/serverEntry.js app[0]
Error: Failed to compile with errors.
    at webpack (/Users/uc/ucwork/ucdevelopers/node_modules/_@vuepress_core@1.0.0-alpha.18@@vuepress/core/lib/build.js:99:18)
    at finalCallback (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/MultiCompiler.js:270:6)
    at done (/Users/uc/ucwork/ucdevelopers/node_modules/_neo-async@2.6.0@neo-async/async.js:2928:13)
    at runCompilers (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/MultiCompiler.js:174:48)
    at err (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/Compiler.js:226:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/uc/ucwork/ucdevelopers/node_modules/_tapable@1.1.0@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/uc/ucwork/ucdevelopers/node_modules/_tapable@1.1.0@tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/Compiler.js:224:21)
    at hooks.afterCompile.callAsync.err (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/uc/ucwork/ucdevelopers/node_modules/_tapable@1.1.0@tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/uc/ucwork/ucdevelopers/node_modules/_tapable@1.1.0@tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/uc/ucwork/ucdevelopers/node_modules/_webpack@4.23.1@webpack/lib/Compiler.js:549:30)
```

#### Other relevant information

- Your OS:  macOS
- Node.js version: 8.11.2
- Browser version:  Chrome 69.0.3497.100
- Is this a global or local install? local
- Which package manager did you use for the install? tnpm

**Comment by youxfans** [comment]
@vuepress/core@1.0.0-alpha.18 › cache-loader@^1.2.2(1.2.4)

cache-loader@1.2.4 is ERR!

**Comment by youxfans** [comment]
in @vuepress/core/package.json
```
// bad
"cache-loader": "^1.2.2",
// good
"cache-loader": "1.2.2",
```

**Comment by ulivz** [comment]
Using `resolutions`:

```
  "resolutions": {
    "cache-loader": "1.2.2",
  },
```

Or try again since cache-loader has fixed it. 🙂

**Comment by youxfans** [comment]
Resolutions can lock the version?  >-<
